/** Server-only AI menu designer helpers. */
const GATEWAY_URL="https://ai.gateway.lovable.dev/v1/responses";
export const MENU_MODEL="openai/gpt-5.6-luna";
export const DESIGN_SCHEMA=`Return {"designs":[d1,d2,d3]} and nothing else.
Each design must contain the existing MenuTheme keys plus a composition object.
composition = {version:2,concept:string,artDirection:string,referenceAnalysis?:{matchLevel:string,layout:string,typography:string,color:string,imagery:string,details:string},background:{color:string,texture:string},elements:[...],responsive?:{mobile:string,tablet:string,desktop:string},motion?:{entrance:string,hover:string,scroll:string}}.
Each element = {id:string,type:title|eyebrow|image|copy|category|product|price|shape,x:number,y:number,w:number,h:number,rotation?:number,opacity?:number,text?:string,image?:string,color?:string,fontSize?:number,fontFamily?:string,fontWeight?:number,letterSpacing?:number,lineHeight?:number,align?:left|center|right,shape?:square|rounded|circle|organic,z?:number,animation?:string}.
Coordinates are percentages of the artboard. Elements must form a real visual composition, not a card list.
Also set theme keys with these exact allowed values: template = classic|midnight|street|cafe|bold|chalkboard|sketch|bifold|editorial|breakfast|bakery|poster|coffeehouse|emerald|script|retro|brush|nautical|ornate|tiles|wellness|duotone|gastro|terracotta|maroon|cocoa|playful; layout = list|grid|magazine|columns|gallery|mosaic|spotlight|rail|ticket|duo|triptych|panel; hero = cover|gradient|minimal|chalk|stamp|ribbon|blob|sidebar|medallion|spine|banner.
The composition and theme together are the editable design source of truth.`;
export const ART_DIRECTION=`You are QuickServe's elite restaurant art director, visual designer and design-systems expert with 25+ years of real hospitality, editorial, branding, typography, food-photography and digital-menu experience.
CORE RULE: THE USER'S INPUT IS THE SOURCE OF TRUTH. If the user supplies a prompt, obey its actual visual instructions. If the user supplies an image, inspect that image carefully and reproduce its visual structure. Do not silently fall back to a house template.
PROMPT INTERPRETATION: Treat every visual instruction as an editable design requirement: font/typeface character, font weight, typography hierarchy, layout, grid, columns, alignment, spacing, colors, gradients, texture, borders, shadows, imagery, image crop, shapes, decorative details, animation, interaction, density, RTL/LTR behavior and overall style. If the user asks to change one property, change that property and preserve everything else unless a dependent adjustment is necessary. If the user asks for a completely different design, change the composition strategy, typography, image treatment and visual rhythm, not just the palette. Never answer a creative prompt with the same default composition.
IMAGE REFERENCE INTERPRETATION: Treat an attached image as the visual source of truth, not generic inspiration. Inspect canvas ratio, placement relationships, dominant/secondary colors, apparent font class, weight, letter spacing, line height, hierarchy, grid, margins, padding, alignment, image positions, crop ratios, radii, strokes, shadows, texture, decorative motifs, section treatment, price treatment, rhythm and negative space. Reconstruct those relationships as editable elements. When the user says exact/same/recreate/copy, maximize visual fidelity. Never put the reference screenshot behind the menu. Preserve restaurant content while following the reference hierarchy.
HUMAN / REALISTIC DESIGN BAR: Make the result look designed by an excellent human designer, not generated from a SaaS template. Avoid repetitive rounded cards, generic centered headers, excessive pills, symmetrical grids and predictable logo-at-top layouts unless requested. Use editorial asymmetry, intentional negative space, varied scale, believable typographic contrast, art-directed food imagery, subtle material texture, imperfect-but-controlled details and strong visual rhythm when appropriate. Food imagery must feel photographed and commercially art-directed. Typography must have a reason. Arabic must have correct RTL hierarchy. Animation must be intentional and subtle.
DIVERSITY RULE: Every generation must be meaningfully different unless exact recreation is requested. Do not use a fixed set of archetypes. Invent the visual direction from the current prompt/reference, restaurant identity, content density and variation seed.
QUALITY CHECK: Does it answer the prompt/reference? Did requested properties change? Is variation material? Is it publishable? Are meaningful parts editable?
Return JSON only.`;
export async function callMenuDesigner(input: unknown[],apiKey:string):Promise<string>{
 const response=await fetch(GATEWAY_URL,{method:"POST",headers:{"Content-Type":"application/json","Lovable-API-Key":apiKey,"X-Lovable-AIG-SDK":"fetch"},body:JSON.stringify({model:MENU_MODEL,input,stream:true,store:false,max_output_tokens:8000})});
 if(!response.ok||!response.body){const details=await response.text().catch(()=>"");console.error("AI menu designer gateway error",response.status,details.slice(0,500));if(response.status===429)throw new Error("The AI designer is busy right now. Please try again in a moment.");if(response.status===402)throw new Error("AI credits are exhausted. Add credits to keep using the AI menu designer.");if(response.status===403)throw new Error("AI access is blocked for this workspace.");if(response.status===401)throw new Error("AI menu designer is not configured correctly.");throw new Error("AI menu generation is temporarily unavailable.");}
 const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";let text="";let completedText="";
 const consume=(line:string)=>{if(!line.startsWith("data:"))return;const payload=line.slice(5).trim();if(!payload||payload==="[DONE]")return;try{const event=JSON.parse(payload) as {type?:string;delta?:string;text?:string;response?:{output_text?:string;output?:Array<{content?:Array<{text?:string}>}>}};if(event.type==="response.output_text.delta"&&typeof event.delta==="string")text+=event.delta;else if(event.type==="response.output_text.done"&&typeof event.text==="string")completedText=event.text;else if(event.type==="response.completed"&&event.response?.output_text)completedText=event.response.output_text;}catch{}}
 for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()??"";for(const line of lines)consume(line);}
 if(buffer)consume(buffer);if(!text&&completedText)text=completedText;if(!text)throw new Error("AI menu designer returned an empty design response.");return text;
}
export function extractDesigns(text:string):Record<string,unknown>[] {const cleaned=text.replace(/^```(?:json)?\s*/i,"").replace(/```$/i,"").trim();const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start<0||end<=start)return[];try{const parsed=JSON.parse(cleaned.slice(start,end+1)) as {designs?:unknown};return Array.isArray(parsed.designs)?parsed.designs.filter((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==="object"):[];}catch{return[];}}
