project_id = "gtcmyaksmyiarokloyje"

[functions.quickserve-api]
verify_jwt = false

[functions.quickserve-campaign-worker]
verify_jwt = false

[functions.quickserve-payments]
verify_jwt = false

[functions.quickserve-stripe-webhook]
verify_jwt = false

[functions.quickserve-integration-worker]
verify_jwt = false

[functions.quickserve-booking-worker]
verify_jwt = false

[functions.quickserve-waitlist-worker]
verify_jwt = false

[functions.quickserve-booking-message-worker]
verify_jwt = false

[functions.quickserve-twilio-booking-webhook]
verify_jwt = false
