import { createFileRoute, useNavigate, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Eye, EyeOff, Globe2, Loader2, LockKeyhole, Mail, UsersRound, UtensilsCrossed, WifiOff } from "lucide-react";
import { toast } from "sonner";
import { z } from "zod";

import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable/index";
import { useI18n } from "@/lib/i18n";
import { BrandLogo } from "@/components/brand/BrandLogo";
import { ThemeToggle } from "@/components/nav/ThemeToggle";
import { humanError } from "@/lib/errors";
import { roleDestination } from "@/lib/post-signin";
import { Input } from "@/components/ui/input";
import { safeSessionRedirect } from "@/lib/session-token";

const searchSchema = z.object({ redirect: z.string().optional() });
export const Route = createFileRoute("/auth")({ validateSearch: searchSchema, head: () => ({ meta: [{ title: "QuickServe sign in" }, { name: "description", content: "Sign in to QuickServe restaurant management and staff operations." }] }), component: AuthPage });
function isNetworkError(error: unknown){const raw=error instanceof Error?error.message:String(error??"");return /failed to fetch|network|load failed|fetch failed|econn|enotfound|timeout/i.test(raw)}
function authFailureMessage(error: unknown,lang:"en"|"ar"){if(isNetworkError(error)){if(typeof navigator!=="undefined"&&!navigator.onLine)return lang==="ar"?"لا يوجد اتصال بالإنترنت. تحقق من اتصالك ثم حاول مرة أخرى.":"You appear to be offline. Check your internet connection and try again.";return lang==="ar"?"خدمة QuickServe غير متاحة مؤقتاً. حاول مرة أخرى بعد قليل.":"QuickServe is temporarily unavailable. Please try again in a moment."}return humanError(error,lang)}

function AuthPage(){
  const {t,lang,toggleLang}=useI18n(); const ar=lang==="ar"; const navigate=useNavigate(); const search=Route.useSearch(); const target=safeSessionRedirect(search.redirect);
  const [mode,setMode]=useState<"signin"|"signup">("signin"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [remember,setRemember]=useState(true); const [busy,setBusy]=useState(false); const [errorMessage,setErrorMessage]=useState<string|null>(null);
  useEffect(()=>{let cancelled=false;void(async()=>{try{const {getResilientAuthenticatedUser}=await import("@/lib/auth-resilience");const user=await getResilientAuthenticatedUser();if(!cancelled&&user){const destination=await roleDestination(target,user.id);if(!cancelled)await navigate({to:destination as never,replace:true})}}catch(error){console.warn("Unable to restore the existing session.",error)}})();return()=>{cancelled=true}},[navigate,target]);
  async function handleSubmit(e:React.FormEvent){e.preventDefault();if(busy)return;const normalizedEmail=email.trim().toLowerCase();if(!normalizedEmail||!password)return;setErrorMessage(null);setBusy(true);try{if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email:normalizedEmail,password,options:{data:{full_name:name.trim()},emailRedirectTo:`${window.location.origin}${target}`}});if(error)throw error;if(data.session){const destination=await roleDestination(target,data.user?.id??data.session.user.id);navigate({to:destination as never,replace:true})}else{toast.success(t("auth.checkEmail"));setMode("signin")}}else{const {data,error}=await supabase.auth.signInWithPassword({email:normalizedEmail,password});if(error)throw error;if(!data.session)throw new Error("Authentication succeeded but no session was created. Please try again.");const destination=await roleDestination(target,data.user?.id??data.session.user.id);navigate({to:destination as never,replace:true})}}catch(error){const message=authFailureMessage(error,lang);setErrorMessage(message);toast.error(message)}finally{setBusy(false)}}
  async function handleGoogle(){if(busy)return;setErrorMessage(null);setBusy(true);try{const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:`${window.location.origin}${target}`});if(result.error)throw result.error;if(result.redirected)return;const destination=await roleDestination(target);navigate({to:destination as never,replace:true})}catch(error){const message=authFailureMessage(error,lang);setErrorMessage(message);toast.error(message)}finally{setBusy(false)}}
  async function forgotPassword(){const normalizedEmail=email.trim().toLowerCase();if(!normalizedEmail){toast.error(ar?"أدخل بريدك الإلكتروني أولاً.":"Enter your email address first.");return}try{const {error}=await supabase.auth.resetPasswordForEmail(normalizedEmail,{redirectTo:`${window.location.origin}/auth`});if(error)throw error;toast.success(ar?"تم إرسال رابط إعادة تعيين كلمة المرور.":"Password reset link sent.")}catch(error){toast.error(authFailureMessage(error,lang))}}

  return <main dir="ltr" className="min-h-dvh bg-[#fbfbfa] p-0 lg:p-5 dark:bg-[#0f1418]">
    <div className="mx-auto min-h-dvh max-w-[1540px] overflow-hidden bg-card lg:min-h-[calc(100dvh-40px)] lg:rounded-[22px] lg:border lg:border-border lg:shadow-[0_24px_70px_rgba(15,23,42,.07)]">
      <header className="flex h-[74px] items-center justify-between border-b border-border px-5 sm:px-8"><Link to="/" aria-label="QuickServe home"><BrandLogo className="size-9" accentClassName="text-[#ff5a0a]" textClassName="text-[22px] text-foreground"/></Link><div className="flex items-center gap-2"><button type="button" onClick={toggleLang} className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-semibold text-muted-foreground hover:bg-muted"><Globe2 className="size-4"/>{ar?"العربية":"English"}</button><ThemeToggle compact/></div></header>
      <div className="grid min-h-[calc(100dvh-116px)] lg:grid-cols-[47%_53%]">
        <section dir={ar?"rtl":"ltr"} className="flex flex-col justify-center px-6 py-10 sm:px-12 lg:px-[5vw]">
          <div className="mx-auto w-full max-w-[540px]">
            <p className="text-[10px] font-bold uppercase tracking-[.28em] text-muted-foreground">{ar?"مرحباً بك في QuickServe":"Welcome to QuickServe"}</p>
            <h1 className="mt-4 font-display text-[clamp(2.1rem,3.6vw,3.7rem)] font-bold leading-[1.02] tracking-[-.055em]">{mode==="signup"?(ar?"أنشئ حسابك":"Create your account"):(ar?"سجّل الدخول إلى حسابك":"Sign in to your account")}</h1>
            <p className="mt-4 max-w-md text-[15px] leading-7 text-muted-foreground">{ar?"أدر مطعمك وفريقك وطلباتك — كل ذلك في مكان واحد.":"Manage your restaurant, team and orders — all in one place."}</p>
            <form onSubmit={handleSubmit} className="mt-8 space-y-5" noValidate>
              {mode==="signup"?<label className="block space-y-2" htmlFor="name"><span className="text-sm font-semibold">{t("auth.name")}</span><Input id="name" value={name} onChange={e=>setName(e.target.value)} required autoComplete="name" disabled={busy} className="h-[56px] rounded-xl"/></label>:null}
              <label className="block space-y-2" htmlFor="email"><span className="text-sm font-semibold">{ar?"البريد الإلكتروني":"Email address"}</span><div className="relative"><Mail className="pointer-events-none absolute start-4 top-1/2 size-[18px] -translate-y-1/2 text-muted-foreground"/><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@restaurant.com" required autoComplete="email" disabled={busy} className="h-[56px] rounded-xl ps-12" dir="ltr"/></div></label>
              <label className="block space-y-2" htmlFor="password"><span className="text-sm font-semibold">{t("auth.password")}</span><div className="relative"><LockKeyhole className="pointer-events-none absolute start-4 top-1/2 size-[18px] -translate-y-1/2 text-muted-foreground"/><Input id="password" type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder={ar?"أدخل كلمة المرور":"Enter your password"} required minLength={8} autoComplete={mode==="signup"?"new-password":"current-password"} disabled={busy} className="h-[56px] rounded-xl ps-12 pe-12" dir="ltr"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute end-3 top-1/2 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-muted-foreground hover:bg-muted">{showPassword?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div></label>
              {mode==="signin"?<div className="flex items-center justify-between gap-3 text-sm"><label className="flex cursor-pointer items-center gap-2 text-muted-foreground"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="size-[17px] accent-[#ff5a0a]"/><span>{ar?"تذكرني":"Remember me"}</span></label><button type="button" onClick={()=>void forgotPassword()} className="font-semibold text-[#ff5a0a] hover:underline">{ar?"نسيت كلمة المرور؟":"Forgot password?"}</button></div>:null}
              <button type="submit" disabled={busy} className="qs-button-primary h-[56px] w-full text-[15px]">{busy?<Loader2 className="size-5 animate-spin"/>:<>{mode==="signup"?t("auth.signUp"):t("auth.signIn")}<ArrowRight className="size-5"/></>}</button>
            </form>
            <div className="my-6 flex items-center gap-4 text-[10px] font-semibold text-muted-foreground"><span className="h-px flex-1 bg-border"/><span>{t("auth.or")}</span><span className="h-px flex-1 bg-border"/></div>
            <button type="button" onClick={()=>void handleGoogle()} disabled={busy} className="flex h-13 min-h-[52px] w-full items-center justify-center gap-3 rounded-xl border border-border bg-card text-sm font-semibold transition hover:bg-muted/40"><span className="grid size-7 place-items-center rounded-full bg-muted font-bold">G</span>{t("auth.google")}</button>
            <Link to="/staff" className="mt-3 flex min-h-[68px] items-center gap-3 rounded-xl border border-orange-100 bg-[#fff6f0] px-4 dark:border-orange-950/50 dark:bg-orange-950/20"><span className="grid size-10 place-items-center rounded-full bg-white text-[#ff5a0a] shadow-sm dark:bg-slate-900"><UsersRound className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{ar?"وصول الموظفين السريع":"Staff quick access"}</strong><span className="mt-1 block text-xs text-muted-foreground">{ar?"الدخول باستخدام رمز الموظف":"Sign in with your staff code"}</span></span><ArrowRight className="size-4 text-muted-foreground"/></Link>
            {errorMessage?<div role="alert" className="mt-4 flex items-start gap-3 rounded-xl border border-border bg-muted/50 px-4 py-3 text-sm"><span className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-full bg-foreground text-background">{isNetworkError(errorMessage)?<WifiOff className="size-3.5"/>:"!"}</span><span className="leading-5">{errorMessage}</span></div>:null}
            <p className="mt-6 text-center text-sm text-muted-foreground">{mode==="signup"?t("auth.haveAccount"):(ar?"ليس لديك حساب؟":"Don't have an account?")} {" "}<button type="button" onClick={()=>{setMode(v=>v==="signup"?"signin":"signup");setErrorMessage(null)}} className="font-semibold text-[#ff5a0a] hover:underline">{mode==="signup"?t("auth.signIn"):t("auth.signUp")}</button></p>
          </div>
        </section>

        <section className="relative hidden overflow-hidden p-5 lg:block">
          <img src="/signin-restaurant.webp" alt="" className="absolute inset-5 size-[calc(100%-40px)] rounded-[20px] object-cover" loading="eager"/>
          <div className="absolute inset-5 rounded-[20px] bg-gradient-to-t from-black/75 via-black/25 to-black/10"/>
          <div className="absolute inset-x-14 bottom-14 z-10 text-white"><div className="mb-8 ms-auto max-w-[270px] rotate-[-4deg] font-display text-[34px] font-semibold leading-[1.08]">Great Food<br/>Happier People<span className="mt-3 block h-1 w-24 rounded-full bg-[#ff5a0a]"/></div><div className="grid max-w-[470px] gap-3"><Benefit icon={<UtensilsCrossed className="size-5"/>} title="Run Smarter" text="Simplify daily operations"/><Benefit icon={<UsersRound className="size-5"/>} title="Grow Together" text="Empower your team"/><Benefit icon={<BarChart3 className="size-5"/>} title="Serve Better" text="Create memorable experiences"/></div><p className="mt-8 text-sm text-white/85">Good Food.<br/>A Brighter Tomorrow.</p></div>
        </section>
      </div>
      <footer className="hidden h-[42px] items-center justify-between border-t border-border px-7 text-[10px] text-muted-foreground lg:flex"><span>QuickServe © 2026. Powering great restaurants.</span><span className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Support</a><a href="#">Contact</a></span></footer>
    </div>
  </main>;
}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-xl bg-black/40 text-[#ff6a22] backdrop-blur-md">{icon}</span><span><strong className="block text-base">{title}</strong><span className="text-xs text-white/75">{text}</span></span></div>}
