import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Archive, ChevronRight, ExternalLink, MapPin, MoreHorizontal, Pencil, Plus, Search, Settings, Store, X } from "lucide-react";
import { toast } from "sonner";

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { useRestaurantsWithStats } from "@/hooks/useSuperAdmin";
import { supabase } from "@/integrations/supabase/client";
import { humanError } from "@/lib/errors";
import { formatMoney, formatNumber } from "@/lib/format";
import { useI18n } from "@/lib/i18n";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/super-admin/restaurants/")({ head: () => ({ meta: [{ title: "Branches / Restaurants — QuickServe" }] }), component: RestaurantsPage });

type LocationFields = { google_maps_url?: string|null; google_place_id?: string|null; latitude?: number|null; longitude?: number|null };
function locationFor(restaurant:{name:string;address_en:string|null;address_ar:string|null}&LocationFields){const lat=Number(restaurant.latitude),lng=Number(restaurant.longitude);const has=Number.isFinite(lat)&&Number.isFinite(lng)&&restaurant.latitude!=null&&restaurant.longitude!=null;const query=has?`${lat},${lng}`:restaurant.address_en||restaurant.address_ar||restaurant.name;return {query,mapUrl:restaurant.google_maps_url?.trim()||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}${restaurant.google_place_id?`&query_place_id=${encodeURIComponent(restaurant.google_place_id)}`:""}`,embedUrl:`https://www.google.com/maps?q=${encodeURIComponent(query)}&output=embed`};}

function RestaurantsPage(){
  const {lang}=useI18n(); const ar=lang==="ar"; const navigate=useNavigate(); const qc=useQueryClient(); const restaurants=useRestaurantsWithStats();
  const [term,setTerm]=useState(""); const [selectedId,setSelectedId]=useState<string|null>(null);
  const data=restaurants.data??[];
  const filtered=useMemo(()=>{const q=term.trim().toLowerCase();return data.filter(r=>!q||[r.name,r.slug,r.address_en,r.address_ar,r.email,r.phone].filter(Boolean).join(" ").toLowerCase().includes(q));},[data,term]);
  const selected=data.find(r=>r.id===selectedId)??filtered[0]??null; const loc=selected?locationFor(selected as typeof selected&LocationFields):null;
  function open(id:string){void navigate({to:"/super-admin/restaurants/$restaurantId",params:{restaurantId:id}})}
  async function archive(id:string,name:string){if(!confirm(ar?`أرشفة ${name}؟`:`Archive ${name}?`))return;try{const {error}=await supabase.from("restaurants").update({archived_at:new Date().toISOString(),is_active:false}).eq("id",id);if(error)throw error;await qc.invalidateQueries({queryKey:["platform","restaurants"]});toast.success(ar?"تمت أرشفة الفرع":"Branch archived");}catch(error){toast.error(humanError(error,lang));}}

  return <div className="space-y-5">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="qs-page-title">{ar?"الفروع / المطاعم":"Branches / Restaurants"}</h1><p className="qs-page-subtitle">{ar?"أدر جميع مواقع مطاعمك من مكان واحد.":"Manage all your restaurant locations from one place."}</p></div><Link to="/super-admin/restaurants/new" className="qs-button-primary"><Plus className="size-4" />{ar?"إضافة فرع":"Add Branch"}</Link></header>

    <div className={cn("grid gap-4",selected?"xl:grid-cols-[minmax(0,1fr)_350px]":"grid-cols-1")}>
      <section className="qs-card min-w-0 overflow-hidden">
        <div className="grid gap-3 border-b border-border p-4 sm:grid-cols-[minmax(0,1fr)_140px_140px_auto]"><div className="relative"><Search className="pointer-events-none absolute start-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={term} onChange={e=>setTerm(e.target.value)} placeholder={ar?"ابحث في الفروع أو الموقع أو الكود...":"Search branches, location, or code..."} className="h-11 ps-10"/></div><button className="qs-control hidden px-3 text-start text-xs font-semibold sm:block">{ar?"كل الحالات":"All Status"}⌄</button><button className="qs-control hidden px-3 text-start text-xs font-semibold sm:block">{ar?"كل الخطط":"All Plans"}⌄</button><span className="hidden place-items-center text-xs text-muted-foreground lg:grid">{filtered.length} {ar?"فروع":"branches"}</span></div>
        {restaurants.isPending?<Skeleton className="m-4 h-[500px] rounded-xl"/>:<>
          <div className="hidden overflow-x-auto md:block"><table className="qs-table min-w-[850px]"><thead><tr><th>{ar?"الفرع":"Branch"}</th><th>{ar?"الموقع":"Location"}</th><th>{ar?"الكود":"Code"}</th><th>{ar?"الحالة":"Status"}</th><th>{ar?"الخطة":"Plan"}</th><th>{ar?"الطلبات":"Orders"}</th><th>{ar?"الإيراد":"Revenue"}</th><th/></tr></thead><tbody>{filtered.map(r=>{const active=r.is_active&&!r.archived_at;const location=locationFor(r as typeof r&LocationFields);return <tr key={r.id} onClick={()=>setSelectedId(r.id)} onDoubleClick={()=>open(r.id)} className={cn("cursor-pointer",selected?.id===r.id&&"outline outline-1 -outline-offset-1 outline-[#ff5a0a] bg-orange-500/[.04]")}><td><div className="flex items-center gap-3"><Logo r={r}/><div className="min-w-0"><p className="truncate font-bold">{r.name}</p><p className="truncate text-[10px] text-muted-foreground">/{r.slug}</p></div></div></td><td><span className="flex max-w-[180px] items-start gap-1.5 text-xs text-muted-foreground"><MapPin className="mt-0.5 size-3.5 shrink-0"/><span className="line-clamp-2">{lang==='ar'?r.address_ar||r.address_en||'—':r.address_en||r.address_ar||'—'}</span></span></td><td className="font-mono text-xs text-muted-foreground">{r.slug.toUpperCase().slice(0,6)}</td><td><Status active={active} ar={ar}/></td><td><span className="qs-status bg-blue-500/10 text-blue-600 capitalize">{r.subscription_plan}</span></td><td className="font-bold">{formatNumber(r.orderCount,lang)}</td><td className="font-bold">{formatMoney(r.revenue,r.currency,lang)}</td><td onClick={e=>e.stopPropagation()}><Actions r={r} loc={location} ar={ar} archive={archive}/></td></tr>})}</tbody></table></div>
          <div className="space-y-2 p-3 md:hidden">{filtered.map(r=>{const active=r.is_active&&!r.archived_at;return <button key={r.id} type="button" onClick={()=>setSelectedId(r.id)} className={cn("flex w-full items-center gap-3 rounded-xl border p-3 text-start",selected?.id===r.id?"border-[#ff5a0a] bg-orange-500/[.04]":"border-border")}><Logo r={r}/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{r.name}</strong><span className="block truncate text-xs text-muted-foreground">{lang==='ar'?r.address_ar||r.address_en||`/${r.slug}`:r.address_en||r.address_ar||`/${r.slug}`}</span></span><Status active={active} ar={ar}/><ChevronRight className="size-4 text-muted-foreground"/></button>})}</div>
        </>}
        <div className="border-t border-border px-4 py-3 text-xs text-muted-foreground">{ar?`عرض ${filtered.length} من ${data.length} فروع`:`Showing ${filtered.length} of ${data.length} branches`}</div>
      </section>

      {selected&&loc?<aside className="qs-right-panel self-start xl:sticky xl:top-24"><div className="qs-panel-header"><div className="flex min-w-0 items-center gap-3"><Logo r={selected}/><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-display text-base font-bold">{selected.name}</h2><Status active={selected.is_active&&!selected.archived_at} ar={ar}/></div><p className="mt-1 text-[10px] text-muted-foreground">/{selected.slug}</p></div></div><button className="grid size-9 place-items-center rounded-lg hover:bg-muted" onClick={()=>setSelectedId(null)}><X className="size-4"/></button></div><div className="flex gap-5 border-b border-border px-4 text-xs font-semibold"><button className="min-h-11 border-b-2 border-[#ff5a0a] text-[#ff5a0a]">{ar?"نظرة عامة":"Overview"}</button><button className="min-h-11 text-muted-foreground">{ar?"الموقع":"Location"}</button><button className="min-h-11 text-muted-foreground">{ar?"الإعدادات":"Settings"}</button></div><div className="space-y-4 p-4"><div className="relative overflow-hidden rounded-xl border border-border"><iframe title={`${selected.name} map`} src={loc.embedUrl} className="h-[205px] w-full border-0" loading="lazy"/><a href={loc.mapUrl} target="_blank" rel="noreferrer" className="absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-2 text-[10px] font-bold text-slate-800 shadow"><ExternalLink className="size-3"/>{ar?"فتح في Google Maps":"Open in Google Maps"}</a></div><Info icon={<MapPin className="size-4"/>} label={ar?"العنوان":"Address"} value={lang==='ar'?selected.address_ar||selected.address_en||loc.query:selected.address_en||selected.address_ar||loc.query}/><Info icon={<ExternalLink className="size-4"/>} label="Google Maps Link" value={selected.google_maps_url||loc.mapUrl} link={loc.mapUrl}/><div className="grid grid-cols-2 gap-3"><Mini label={ar?"الطلبات (30 يوم)":"Orders (30 days)"} value={formatNumber(selected.orderCount,lang)}/><Mini label={ar?"الإيراد (30 يوم)":"Revenue (30 days)"} value={formatMoney(selected.revenue,selected.currency,lang)}/></div><Info icon={<Store className="size-4"/>} label={ar?"الخطة":"Plan"} value={selected.subscription_plan}/><div className="grid grid-cols-2 gap-2 border-t border-border pt-4"><Link to="/super-admin/restaurants/$restaurantId/edit" params={{restaurantId:selected.id}} className="qs-button-secondary"><Pencil className="size-4"/>{ar?"تعديل":"Edit"}</Link><Link to="/super-admin/restaurants/$restaurantId" params={{restaurantId:selected.id}} className="qs-button-primary"><Settings className="size-4"/>{ar?"إدارة":"Manage"}</Link></div></div></aside>:null}
    </div>
  </div>;
}

function Logo({r}:{r:{logo_url:string|null;name:string}}){return <span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full border border-border bg-muted">{r.logo_url?<img src={r.logo_url} alt="" className="size-full object-cover"/>:<Store className="size-4 text-[#ff5a0a]"/>}</span>}
function Status({active,ar}:{active:boolean;ar:boolean}){return <span className={cn("qs-status",active?"bg-emerald-500/12 text-emerald-600":"bg-rose-500/12 text-rose-600")}><i className={cn("size-1.5 rounded-full",active?"bg-emerald-500":"bg-rose-500")}/>{active?(ar?"نشط":"Active"):(ar?"غير نشط":"Inactive")}</span>}
function Actions({r,loc,ar,archive}:{r:{id:string;name:string};loc:{mapUrl:string};ar:boolean;archive:(id:string,name:string)=>Promise<void>}){return <DropdownMenu><DropdownMenuTrigger asChild><button className="grid size-9 place-items-center rounded-lg hover:bg-muted"><MoreHorizontal className="size-4"/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link to="/super-admin/restaurants/$restaurantId" params={{restaurantId:r.id}}><Store className="size-4"/>{ar?"فتح":"Open"}</Link></DropdownMenuItem><DropdownMenuItem asChild><Link to="/super-admin/restaurants/$restaurantId/edit" params={{restaurantId:r.id}}><Pencil className="size-4"/>{ar?"تعديل / إعادة تسمية":"Edit / Rename"}</Link></DropdownMenuItem><DropdownMenuItem asChild><a href={loc.mapUrl} target="_blank" rel="noreferrer"><MapPin className="size-4"/>{ar?"عرض الخريطة":"View Map"}</a></DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onSelect={()=>void archive(r.id,r.name)}><Archive className="size-4"/>{ar?"حذف / أرشفة":"Delete / Archive"}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
function Info({icon,label,value,link}:{icon:React.ReactNode;label:string;value:string;link?:string}){return <div className="flex gap-3 rounded-xl border border-border p-3"><span className="mt-0.5 text-muted-foreground">{icon}</span><div className="min-w-0 flex-1"><p className="text-[10px] text-muted-foreground">{label}</p>{link?<a href={link} target="_blank" rel="noreferrer" className="mt-1 block truncate text-xs font-semibold text-blue-600">{value}</a>:<p className="mt-1 text-xs font-semibold leading-5">{value}</p>}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 truncate font-display text-lg font-bold">{value}</p><p className="mt-1 text-[10px] font-semibold text-emerald-600">↗ 0%</p></div>}
