import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useState, type ReactNode } from "react";
import { Bell, Building2, Coins, Mail, Palette, Percent, Phone, Shield, ShieldCheck, User } from "lucide-react";
import { toast } from "sonner";
import { StaffHeader } from "@/components/staff/StaffHeader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useAccess } from "@/hooks/useSession";
import { useWorkspaceMembers, useWorkspaceScope } from "@/hooks/useWorkspace";
import { useRestaurant } from "@/hooks/useSuperAdmin";
import { useI18n } from "@/lib/i18n";
import { humanError } from "@/lib/errors";
import { ROLE_LABELS, type AppRole } from "@/lib/permissions";
import type { Database } from "@/integrations/supabase/types";

type RestaurantUpdate = Database["public"]["Tables"]["restaurants"]["Update"];
const NOTIF_KEY = "quickserve.notifications";
const ROLES: AppRole[] = ["restaurant_admin", "manager", "kitchen", "waiter", "cashier"];
type Notifications = { newOrders: boolean; waiterCalls: boolean; sound: boolean; daily: boolean };
const DEFAULT_NOTIF: Notifications = { newOrders: true, waiterCalls: true, sound: true, daily: false };
export const Route = createFileRoute("/_authenticated/profile")({ head: () => ({ meta: [{ title: "Profile & settings — QuickServe" }] }), component: ProfilePage });
function IconField({ icon: Icon, children }: { icon: typeof Building2; children: ReactNode }) { return <div className="relative"><Icon className="pointer-events-none absolute start-3 top-1/2 z-10 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden />{children}</div>; }
function ProfilePage() {
 const { lang } = useI18n(); const navigate = useNavigate(); const queryClient = useQueryClient(); const access = useAccess(); const scope = useWorkspaceScope(); const restaurantId = scope.restaurantId; const { data: restaurant } = useRestaurant(restaurantId ?? ""); const members = useWorkspaceMembers(restaurantId);
 const [email,setEmail]=useState<string|null>(null); const [displayName,setDisplayName]=useState<string|null>(null); const [notif,setNotif]=useState<Notifications>(DEFAULT_NOTIF); const [org,setOrg]=useState({name:"",phone:"",currency:"JOD",tax:"0"}); const [colors,setColors]=useState({primary:"#f59323",accent:"#111111",background:"#ffffff"}); const [saving,setSaving]=useState(false);
 const canManage=access.isSuperAdmin||(access.data??[]).some(m=>m.restaurant_id===restaurantId&&(m.role==="restaurant_admin"||m.role==="manager"));
 useEffect(()=>{void supabase.auth.getUser().then(({data:u})=>{setEmail(u.user?.email??null);const meta=u.user?.user_metadata as {full_name?:string;name?:string}|undefined;setDisplayName(meta?.full_name||meta?.name||null)});try{const raw=window.localStorage.getItem(NOTIF_KEY);if(raw)setNotif({...DEFAULT_NOTIF,...(JSON.parse(raw) as Partial<Notifications>)})}catch{}},[]);
 useEffect(()=>{if(!restaurant)return;setOrg({name:restaurant.name,phone:restaurant.phone??"",currency:restaurant.currency,tax:String(restaurant.tax_rate??0)});setColors({primary:restaurant.primary_color,accent:restaurant.accent_color,background:restaurant.background_color})},[restaurant]);
 function setNotification(key:keyof Notifications,value:boolean){const next={...notif,[key]:value};setNotif(next);window.localStorage.setItem(NOTIF_KEY,JSON.stringify(next));}
 async function saveRestaurant(patch:RestaurantUpdate){if(!restaurantId)return;setSaving(true);try{const{error}=await supabase.from("restaurants").update(patch).eq("id",restaurantId);if(error)throw error;await queryClient.invalidateQueries({queryKey:["platform","restaurant",restaurantId]});toast.success(lang==="ar"?"تم الحفظ":"Saved")}catch(error){toast.error(humanError(error,lang))}finally{setSaving(false)}}
 async function changeRole(staffId:string,role:AppRole){try{const{error}=await supabase.from("staff").update({role}).eq("id",staffId);if(error)throw error;await members.refetch();toast.success(lang==="ar"?"تم تحديث الصلاحية":"Role updated")}catch(error){toast.error(humanError(error,lang))}}
 async function signOut(){await queryClient.cancelQueries();queryClient.clear();await supabase.auth.signOut();navigate({to:"/auth",replace:true});}
 const memberships=(access.data??[]).filter(m=>m.restaurant_id); const nameSource=displayName||email||"?"; const initial=nameSource.slice(0,1).toUpperCase(); const roleBadge=access.isSuperAdmin?ROLE_LABELS.super_admin[lang]:memberships[0]?ROLE_LABELS[memberships[0].role][lang]:null;
 return <div className="min-h-screen bg-background pb-24 lg:pb-8"><StaffHeader title={lang==="ar"?"الملف الشخصي":"Profile"}/><main className="mx-auto w-full max-w-6xl space-y-5 px-3 py-4 sm:px-6 sm:py-6 lg:px-8">
 <section className="rounded-3xl bg-gradient-to-br from-primary/10 via-card to-accent/5 p-1"><div className="panel flex flex-col gap-4 rounded-[1.35rem] p-4 sm:flex-row sm:items-center sm:p-6"><span className="grid size-16 shrink-0 place-items-center rounded-2xl bg-primary/10 text-2xl font-bold text-primary sm:size-20">{initial}</span><div className="min-w-0 flex-1"><p className="truncate text-xl font-bold tracking-tight sm:text-2xl">{displayName||(email??"—")}</p><p className="mt-1 flex items-center gap-2 truncate text-sm text-muted-foreground"><Mail className="size-4 shrink-0"/>{email??"—"}</p>{roleBadge?<Badge variant="secondary" className="mt-2 gap-1"><Shield className="size-3"/>{roleBadge}</Badge>:null}</div>{restaurant?.name?<div className="hidden rounded-2xl border bg-background/70 px-4 py-3 text-end sm:block"><p className="text-[11px] text-muted-foreground">{lang==="ar"?"المطعم":"Restaurant"}</p><p className="mt-1 font-semibold">{restaurant.name}</p></div>:null}</div></section>
 <Tabs defaultValue="organisation" className="w-full"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 rounded-2xl bg-muted/60 p-1 sm:grid-cols-3 lg:grid-cols-5">{([["organisation",Building2,lang==="ar"?"المؤسسة":"Organisation"],["account",User,lang==="ar"?"الحساب":"Account"],["permissions",ShieldCheck,lang==="ar"?"الصلاحيات":"Permissions"],["notifications",Bell,lang==="ar"?"التنبيهات":"Notifications"],["branding",Palette,lang==="ar"?"الهوية":"Branding"]] as const).map(([value,Icon,label])=><TabsTrigger key={value} value={value} className="min-h-12 gap-1.5 rounded-xl px-2 text-xs sm:text-sm data-[state=active]:bg-background data-[state=active]:text-primary data-[state=active]:shadow-sm"><Icon className="size-4"/>{label}</TabsTrigger>)}</TabsList>
 <TabsContent value="organisation" className="mt-4">{restaurantId?<section className="panel space-y-5 p-4 sm:p-6"><div><h2 className="flex items-center gap-2 text-base font-bold"><Building2 className="size-5 text-primary"/>{lang==="ar"?"إعدادات المطعم":"Restaurant settings"}</h2><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"حدّث بيانات المطعم الأساسية.":"Update your restaurant's core details."}</p></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-1.5"><Label>{lang==="ar"?"اسم المطعم":"Restaurant name"}</Label><IconField icon={Building2}><Input className="h-11 ps-9" value={org.name} disabled={!canManage} onChange={e=>setOrg({...org,name:e.target.value})}/></IconField></div><div className="space-y-1.5"><Label>{lang==="ar"?"الهاتف":"Phone"}</Label><IconField icon={Phone}><Input className="h-11 ps-9" value={org.phone} disabled={!canManage} onChange={e=>setOrg({...org,phone:e.target.value})}/></IconField></div><div className="space-y-1.5"><Label>{lang==="ar"?"العملة":"Currency"}</Label><Select value={org.currency} onValueChange={v=>setOrg({...org,currency:v})} disabled={!canManage}><SelectTrigger className="h-11"><span className="flex items-center gap-2"><Coins className="size-4 text-muted-foreground"/><SelectValue/></span></SelectTrigger><SelectContent>{["JOD","SAR","AED","USD","EUR"].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>{lang==="ar"?"نسبة الضريبة %":"Tax rate %"}</Label><IconField icon={Percent}><Input className="h-11 ps-9" type="number" inputMode="decimal" value={org.tax} disabled={!canManage} onChange={e=>setOrg({...org,tax:e.target.value})}/></IconField></div></div>{canManage?<Button disabled={saving} onClick={()=>void saveRestaurant({name:org.name.trim(),phone:org.phone.trim()||null,currency:org.currency,tax_rate:Number(org.tax)||0})}>{lang==="ar"?"حفظ التغييرات":"Save changes"}</Button>:<p className="text-xs text-muted-foreground">{lang==="ar"?"للعرض فقط بصلاحيتك الحالية.":"Read-only for your role."}</p>}</section>:<p className="panel p-5 text-sm text-muted-foreground">{lang==="ar"?"اربط حسابك بمطعم لعرض إعدادات المؤسسة.":"Link your account to a restaurant to see organisation settings."}</p>}</TabsContent>
 <TabsContent value="account" className="mt-4"><section className="panel space-y-5 p-4 sm:p-6"><h2 className="flex items-center gap-2 text-base font-bold"><User className="size-5 text-primary"/>{lang==="ar"?"الحساب":"Account"}</h2><div className="grid gap-4 md:grid-cols-2"><div className="space-y-1.5"><Label>{lang==="ar"?"الاسم":"Name"}</Label><IconField icon={User}><Input className="h-11 ps-9" value={displayName??""} readOnly/></IconField></div><div className="space-y-1.5"><Label>Email</Label><IconField icon={Mail}><Input className="h-11 ps-9" value={email??""} readOnly/></IconField></div></div><Button variant="destructive" onClick={()=>void signOut()}>{lang==="ar"?"تسجيل الخروج":"Sign out"}</Button></section></TabsContent>
 <TabsContent value="permissions" className="mt-4"><section className="panel space-y-4 p-4 sm:p-6"><div><h2 className="flex items-center gap-2 text-base font-bold"><ShieldCheck className="size-5 text-primary"/>{lang==="ar"?"صلاحيات الفريق":"Team permissions"}</h2><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"إدارة أدوار أعضاء المطعم.":"Manage restaurant member roles."}</p></div>{members.isPending?<div className="h-32 animate-pulse rounded-2xl bg-muted"/>:<div className="space-y-2">{(members.data??[]).map(member=><div key={member.id} className="flex flex-col gap-3 rounded-2xl border bg-background p-3 sm:flex-row sm:items-center"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><User className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{member.name||member.email||"—"}</p><p className="truncate text-xs text-muted-foreground">{member.email||"—"}</p></div><Select value={member.role} onValueChange={v=>void changeRole(member.id,v as AppRole)} disabled={!canManage}><SelectTrigger className="h-10 w-full sm:w-44"><SelectValue/></SelectTrigger><SelectContent>{ROLES.map(r=><SelectItem key={r} value={r}>{ROLE_LABELS[r][lang]}</SelectItem>)}</SelectContent></Select></div>)}</div>}</section></TabsContent>
 <TabsContent value="notifications" className="mt-4"><section className="panel space-y-2 p-4 sm:p-6"><h2 className="mb-3 flex items-center gap-2 text-base font-bold"><Bell className="size-5 text-primary"/>{lang==="ar"?"التنبيهات":"Notifications"}</h2>{([ ["newOrders","New orders","طلبات جديدة"],["waiterCalls","Waiter calls","طلبات النادل"],["sound","Notification sound","صوت التنبيه"],["daily","Daily summary","الملخص اليومي"]] as const).map(([key,en,ar])=><label key={key} className="flex min-h-14 cursor-pointer items-center justify-between gap-4 rounded-2xl border px-4 py-3 hover:bg-muted/50"><span className="font-medium">{lang==="ar"?ar:en}</span><input type="checkbox" checked={notif[key]} onChange={e=>setNotification(key,e.target.checked)} className="size-5 accent-[var(--color-primary)]"/></label>)}</section></TabsContent>
 <TabsContent value="branding" className="mt-4"><section className="panel space-y-5 p-4 sm:p-6"><div><h2 className="flex items-center gap-2 text-base font-bold"><Palette className="size-5 text-primary"/>{lang==="ar"?"الهوية البصرية":"Branding"}</h2><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"الألوان الأساسية للمطعم.":"Restaurant brand colors."}</p></div><div className="grid gap-4 sm:grid-cols-3">{([["primary","Primary"],["accent","Accent"],["background","Background"]] as const).map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-2xl border p-3"><input type="color" value={colors[key]} disabled={!canManage} onChange={e=>setColors({...colors,[key]:e.target.value})} className="size-10 cursor-pointer rounded-lg border-0 bg-transparent p-0"/><span><span className="block text-sm font-semibold">{label}</span><span className="text-xs text-muted-foreground">{colors[key]}</span></span></label>)}</div>{canManage?<Button onClick={()=>void saveRestaurant({primary_color:colors.primary,accent_color:colors.accent,background_color:colors.background})}>{lang==="ar"?"حفظ الهوية":"Save branding"}</Button>:null}</section></TabsContent>
 </Tabs></main></div>;
}
