import { ArrowLeft, ArrowRight, BarChart3, CalendarDays, CreditCard, FileText, Receipt, ShoppingBag, Table2, TrendingUp } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { formatDateTime, formatMoney, formatNumber } from "@/lib/format";

export type AnalyticsDetailWidgetId = "revenue" | "orders" | "channels" | "topProducts" | "peakHours" | "weekly" | "orderTable" | "paidProgress" | "summary";
const IDS: AnalyticsDetailWidgetId[] = ["revenue","orders","channels","topProducts","peakHours","weekly","orderTable","paidProgress","summary"];
export function isAnalyticsDetailWidget(value:string|null):value is AnalyticsDetailWidgetId{return Boolean(value&&IDS.includes(value as AnalyticsDetailWidgetId));}

type OrderRow={id:string;order_number:string;status:string;payment_status:string;total:number|string;table_id:string|null;created_at:string};
type ProductRow={name:string;nameAr:string;qty:number;revenue:number};
type SeriesRow={key:string;label:string;sales:number;orders:number};
type WeekRow={label:string;orders:number;sales:number};
type AnalyticsData={orders:OrderRow[];revenue:number;aov:number;paidRate:number;series:SeriesRow[];channels:Array<{name:string;value:number}>;topProducts:ProductRow[];peak:Array<{hour:number;orders:number}>;weekly:WeekRow[];recent:OrderRow[]};

export function AnalyticsDetailPage({widget,restaurantId,labels,data,currency,lang}:{widget:AnalyticsDetailWidgetId;restaurantId:string;labels:Record<AnalyticsDetailWidgetId,string>;data:AnalyticsData;currency:string;lang:"ar"|"en"}){
 const ar=lang==="ar";const BackIcon=ar?ArrowRight:ArrowLeft;const base=`/manage/${restaurantId}/analytics`;
 const channels=buildChannels(data.orders,ar);const hours=buildHours(data.orders);const payments=buildPayments(data.orders);const title=labels[widget];
 return <div className="space-y-5">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Link to={base as never} preload="intent" className="mb-3 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground transition hover:text-[#e85d2a]"><BackIcon className="size-4"/>{ar?"العودة للتحليلات":"Back to Analytics"}</Link><h1 className="qs-page-title">{title}</h1><p className="qs-page-subtitle">{ar?"صفحة مستقلة مبنية على بيانات هذا المطعم الفعلية لآخر 30 يوماً.":"Independent detail view powered by this restaurant’s real data from the last 30 days."}</p></div><span className="qs-button-secondary pointer-events-none"><CalendarDays className="size-4"/>{ar?"آخر 30 يوماً":"Last 30 days"}</span></header>
  <nav className="overflow-x-auto rounded-2xl border border-border bg-card p-1.5"><div className="flex min-w-max gap-1">{IDS.map(id=><Link key={id} to={`${base}/${id}` as never} preload="intent" className={`rounded-xl px-3 py-2.5 text-[11px] font-bold transition ${id===widget?"bg-[#e85d2a] text-white shadow-sm":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{labels[id]}</Link>)}</div></nav>
  {widget==="revenue"?<Revenue ar={ar} lang={lang} currency={currency} data={data} channels={channels}/>:null}
  {widget==="orders"?<Orders ar={ar} lang={lang} currency={currency} data={data}/>:null}
  {widget==="channels"?<Channels ar={ar} lang={lang} currency={currency} rows={channels}/>:null}
  {widget==="topProducts"?<Products ar={ar} lang={lang} currency={currency} rows={data.topProducts}/>:null}
  {widget==="peakHours"?<Peak ar={ar} lang={lang} currency={currency} rows={hours}/>:null}
  {widget==="weekly"?<Weekly ar={ar} lang={lang} currency={currency} rows={data.weekly}/>:null}
  {widget==="orderTable"?<OrderTable ar={ar} lang={lang} currency={currency} rows={data.orders}/>:null}
  {widget==="paidProgress"?<Payments ar={ar} lang={lang} currency={currency} rows={payments} data={data}/>:null}
  {widget==="summary"?<Summary ar={ar} lang={lang} currency={currency} data={data} channels={channels}/>:null}
 </div>;
}

function Revenue({ar,lang,currency,data,channels}:{ar:boolean;lang:"ar"|"en";currency:string;data:AnalyticsData;channels:ChannelRow[]}){const best=data.series.reduce<SeriesRow|null>((best,row)=>!best||row.sales>best.sales?row:best,null);return <><Kpis items={[{label:ar?"الإيراد":"Revenue",value:formatMoney(data.revenue,currency,lang),icon:<TrendingUp/>},{label:ar?"الطلبات":"Orders",value:formatNumber(data.orders.length,lang),icon:<Receipt/>},{label:ar?"متوسط الطلب":"AOV",value:formatMoney(data.aov,currency,lang),icon:<ShoppingBag/>},{label:ar?"أفضل يوم":"Best day",value:best?formatMoney(best.sales,currency,lang):"—",icon:<BarChart3/>}]}/><div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Chart title={ar?"اتجاه الإيراد":"Revenue trend"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><defs><linearGradient id="revFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e85d2a" stopOpacity={.26}/><stop offset="100%" stopColor="#e85d2a" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="label" fontSize={9} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Area dataKey="sales" stroke="#e85d2a" fill="url(#revFill)" strokeWidth={3}/></AreaChart></ResponsiveContainer></Chart><Chart title={ar?"الإيراد حسب القناة":"Revenue by channel"}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={channels} dataKey="revenue" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={4}>{channels.map((_,index)=><Cell key={index} fill={["#e85d2a","#3b82f6","#10b981"][index%3]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Chart></div><Card title={ar?"الإيراد حسب اليوم":"Revenue by day"}><Table headers={[ar?"اليوم":"Day",ar?"الإيراد":"Revenue",ar?"الطلبات":"Orders",ar?"متوسط الطلب":"AOV"]} rows={data.series.map(row=>[row.label,<strong>{formatMoney(row.sales,currency,lang)}</strong>,formatNumber(row.orders,lang),formatMoney(row.orders?row.sales/row.orders:0,currency,lang)])} ar={ar}/></Card></>}
function Orders({ar,lang,currency,data}:{ar:boolean;lang:"ar"|"en";currency:string;data:AnalyticsData}){const status=group(data.orders,row=>row.status);return <><Kpis items={[{label:ar?"الطلبات":"Orders",value:formatNumber(data.orders.length,lang),icon:<Receipt/>},{label:ar?"الإيراد":"Revenue",value:formatMoney(data.revenue,currency,lang),icon:<TrendingUp/>},{label:ar?"متوسط الطلب":"AOV",value:formatMoney(data.aov,currency,lang),icon:<ShoppingBag/>},{label:ar?"مدفوع":"Paid",value:`${Math.round(data.paidRate)}%`,icon:<CreditCard/>}]}/><Chart title={ar?"الطلبات حسب الحالة":"Orders by status"}><ResponsiveContainer width="100%" height="100%"><BarChart data={status}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="name" fontSize={9} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="count" fill="#10b981" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Chart><Card title={ar?"تفاصيل الطلبات":"Order details"}><Table headers={[ar?"الطلب":"Order",ar?"الحالة":"Status",ar?"الدفع":"Payment",ar?"القناة":"Channel",ar?"الإجمالي":"Total",ar?"التاريخ":"Date"]} rows={data.orders.slice().reverse().map(row=>[<strong>{row.order_number}</strong>,<Status value={row.status}/>,<Status value={row.payment_status}/>,row.table_id?(ar?"داخل المطعم":"Dine-in"):(ar?"خارجي":"Takeaway"),formatMoney(Number(row.total),currency,lang),formatDateTime(row.created_at,lang)])} ar={ar}/></Card></>}
function Channels({ar,lang,currency,rows}:{ar:boolean;lang:"ar"|"en";currency:string;rows:ChannelRow[]}){const total=rows.reduce((sum,row)=>sum+row.count,0);return <><Kpis items={rows.slice(0,4).map(row=>({label:row.name,value:formatNumber(row.count,lang),icon:<ShoppingBag/>}))}/><Chart title={ar?"مقارنة القنوات":"Channel comparison"}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="name" fontSize={10} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="revenue" fill="#3b82f6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Chart><Card title={ar?"تفاصيل القنوات":"Channel details"}><Table headers={[ar?"القناة":"Channel",ar?"الطلبات":"Orders",ar?"الإيراد":"Revenue",ar?"الحصة":"Share",ar?"متوسط الطلب":"AOV"]} rows={rows.map(row=>[<strong>{row.name}</strong>,formatNumber(row.count,lang),formatMoney(row.revenue,currency,lang),`${total?Math.round(row.count/total*100):0}%`,formatMoney(row.count?row.revenue/row.count:0,currency,lang)])} ar={ar}/></Card></>}
function Products({ar,lang,currency,rows}:{ar:boolean;lang:"ar"|"en";currency:string;rows:ProductRow[]}){return <><Kpis items={[{label:ar?"منتجات ظاهرة":"Ranked products",value:formatNumber(rows.length,lang),icon:<ShoppingBag/>},{label:ar?"إجمالي الكمية":"Units sold",value:formatNumber(rows.reduce((s,r)=>s+r.qty,0),lang),icon:<Receipt/>},{label:ar?"إيراد أفضل المنتجات":"Top-product revenue",value:formatMoney(rows.reduce((s,r)=>s+r.revenue,0),currency,lang),icon:<TrendingUp/>},{label:ar?"الأفضل":"Top product",value:rows[0]?(ar?rows[0].nameAr:rows[0].name):"—",icon:<BarChart3/>}]}/><Chart title={ar?"أفضل المنتجات بالكمية":"Top products by quantity"}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.slice(0,8)}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey={ar?"nameAr":"name"} fontSize={8} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="qty" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Chart><Card title={ar?"تصنيف المنتجات":"Product ranking"}><Table headers={["#",ar?"المنتج":"Product",ar?"الكمية":"Quantity",ar?"الإيراد":"Revenue",ar?"متوسط قيمة الوحدة":"Avg. unit value"]} rows={rows.map((row,index)=>[<strong>{index+1}</strong>,<strong>{ar?row.nameAr:row.name}</strong>,formatNumber(row.qty,lang),formatMoney(row.revenue,currency,lang),formatMoney(row.qty?row.revenue/row.qty:0,currency,lang)])} ar={ar}/></Card></>}
function Peak({ar,lang,currency,rows}:{ar:boolean;lang:"ar"|"en";currency:string;rows:HourRow[]}){const best=rows.reduce<HourRow|null>((b,r)=>!b||r.orders>b.orders?r:b,null);return <><Kpis items={[{label:ar?"ساعة الذروة":"Peak hour",value:best?`${String(best.hour).padStart(2,"0")}:00`:"—",icon:<BarChart3/>},{label:ar?"طلبات الذروة":"Peak orders",value:best?formatNumber(best.orders,lang):"—",icon:<Receipt/>},{label:ar?"إيراد ساعة الذروة":"Peak revenue",value:best?formatMoney(best.revenue,currency,lang):"—",icon:<TrendingUp/>},{label:ar?"ساعات نشطة":"Active hours",value:formatNumber(rows.length,lang),icon:<CalendarDays/>}]}/><Chart title={ar?"الطلبات حسب الساعة":"Orders by hour"}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="label" fontSize={8} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="orders" fill="#f59e0b" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Chart><Card title={ar?"تفاصيل الساعات":"Hourly performance"}><Table headers={[ar?"الساعة":"Hour",ar?"الطلبات":"Orders",ar?"الإيراد":"Revenue",ar?"متوسط الطلب":"AOV"]} rows={rows.map(row=>[row.label,formatNumber(row.orders,lang),formatMoney(row.revenue,currency,lang),formatMoney(row.orders?row.revenue/row.orders:0,currency,lang)])} ar={ar}/></Card></>}
function Weekly({ar,lang,currency,rows}:{ar:boolean;lang:"ar"|"en";currency:string;rows:WeekRow[]}){return <><Kpis items={[{label:ar?"إيراد الأسبوع":"Weekly revenue",value:formatMoney(rows.reduce((s,r)=>s+r.sales,0),currency,lang),icon:<TrendingUp/>},{label:ar?"طلبات الأسبوع":"Weekly orders",value:formatNumber(rows.reduce((s,r)=>s+r.orders,0),lang),icon:<Receipt/>},{label:ar?"أفضل يوم":"Best weekday",value:rows.reduce<WeekRow|null>((b,r)=>!b||r.sales>b.sales?r:b,null)?.label??"—",icon:<CalendarDays/>},{label:ar?"أيام مقاسة":"Measured days",value:formatNumber(rows.length,lang),icon:<BarChart3/>}]}/><Chart title={ar?"الإيراد الأسبوعي":"Weekly revenue"}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="label" fontSize={9} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="sales" fill="#06b6d4" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Chart><Card title={ar?"الأداء حسب يوم الأسبوع":"Performance by weekday"}><Table headers={[ar?"اليوم":"Day",ar?"الطلبات":"Orders",ar?"الإيراد":"Revenue",ar?"متوسط الطلب":"AOV"]} rows={rows.map(row=>[<strong>{row.label}</strong>,formatNumber(row.orders,lang),formatMoney(row.sales,currency,lang),formatMoney(row.orders?row.sales/row.orders:0,currency,lang)])} ar={ar}/></Card></>}
function OrderTable({ar,lang,currency,rows}:{ar:boolean;lang:"ar"|"en";currency:string;rows:OrderRow[]}){return <Card title={ar?"مجموعة بيانات الطلبات":"Orders dataset"}><Table headers={[ar?"الطلب":"Order",ar?"الحالة":"Status",ar?"الدفع":"Payment",ar?"القناة":"Channel",ar?"الإجمالي":"Total",ar?"التاريخ":"Date"]} rows={rows.slice().reverse().map(row=>[<strong>{row.order_number}</strong>,<Status value={row.status}/>,<Status value={row.payment_status}/>,row.table_id?(ar?"داخل المطعم":"Dine-in"):(ar?"خارجي":"Takeaway"),formatMoney(Number(row.total),currency,lang),formatDateTime(row.created_at,lang)])} ar={ar}/></Card>}
function Payments({ar,lang,currency,rows,data}:{ar:boolean;lang:"ar"|"en";currency:string;rows:PaymentRow[];data:AnalyticsData}){return <><Kpis items={[{label:ar?"نسبة المدفوع":"Paid rate",value:`${Math.round(data.paidRate)}%`,icon:<CreditCard/>},{label:ar?"إجمالي القيمة":"Total value",value:formatMoney(data.revenue,currency,lang),icon:<TrendingUp/>},...rows.slice(0,2).map(row=>({label:row.name,value:formatNumber(row.count,lang),icon:<Receipt/>}))]}/><Chart title={ar?"توزيع حالة الدفع":"Payment status distribution"}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="count" nameKey="name" innerRadius={65} outerRadius={96} paddingAngle={4}>{rows.map((_,index)=><Cell key={index} fill={["#10b981","#f59e0b","#64748b"][index%3]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Chart><Card title={ar?"تفاصيل الدفع":"Payment details"}><Table headers={[ar?"الحالة":"Status",ar?"الطلبات":"Orders",ar?"القيمة":"Value",ar?"الحصة":"Share"]} rows={rows.map(row=>[<Status value={row.name}/>,formatNumber(row.count,lang),formatMoney(row.value,currency,lang),`${data.orders.length?Math.round(row.count/data.orders.length*100):0}%`])} ar={ar}/></Card></>}
function Summary({ar,lang,currency,data,channels}:{ar:boolean;lang:"ar"|"en";currency:string;data:AnalyticsData;channels:ChannelRow[]}){return <><Kpis items={[{label:ar?"الإيراد":"Revenue",value:formatMoney(data.revenue,currency,lang),icon:<TrendingUp/>},{label:ar?"الطلبات":"Orders",value:formatNumber(data.orders.length,lang),icon:<Receipt/>},{label:ar?"متوسط الطلب":"AOV",value:formatMoney(data.aov,currency,lang),icon:<ShoppingBag/>},{label:ar?"المدفوع":"Paid rate",value:`${Math.round(data.paidRate)}%`,icon:<CreditCard/>}]}/><div className="grid gap-4 xl:grid-cols-2"><Chart title={ar?"اتجاه الأداء":"Performance trend"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="label" fontSize={9} tickLine={false} axisLine={false}/><YAxis fontSize={9} tickLine={false} axisLine={false}/><Tooltip/><Area dataKey="sales" stroke="#e85d2a" fill="#e85d2a" fillOpacity={.12} strokeWidth={3}/></AreaChart></ResponsiveContainer></Chart><Card title={ar?"ملخص القنوات":"Channel summary"}><Table headers={[ar?"القناة":"Channel",ar?"الطلبات":"Orders",ar?"الإيراد":"Revenue"]} rows={channels.map(row=>[row.name,formatNumber(row.count,lang),formatMoney(row.revenue,currency,lang)])} ar={ar}/></Card></div><Card title={ar?"ملخص يومي تنفيذي":"Executive daily breakdown"}><Table headers={[ar?"اليوم":"Day",ar?"الإيراد":"Revenue",ar?"الطلبات":"Orders",ar?"متوسط الطلب":"AOV"]} rows={data.series.map(row=>[row.label,formatMoney(row.sales,currency,lang),formatNumber(row.orders,lang),formatMoney(row.orders?row.sales/row.orders:0,currency,lang)])} ar={ar}/></Card></>}

type ChannelRow={name:string;count:number;revenue:number};type HourRow={hour:number;label:string;orders:number;revenue:number};type PaymentRow={name:string;count:number;value:number};
function buildChannels(orders:OrderRow[],ar:boolean):ChannelRow[]{const dine=orders.filter(r=>r.table_id);const out=orders.filter(r=>!r.table_id);return [{name:ar?"داخل المطعم":"Dine-in",count:dine.length,revenue:dine.reduce((s,r)=>s+Number(r.total),0)},{name:ar?"خارجي":"Takeaway",count:out.length,revenue:out.reduce((s,r)=>s+Number(r.total),0)}].filter(r=>r.count>0)}
function buildHours(orders:OrderRow[]):HourRow[]{const rows=Array.from({length:24},(_,hour)=>({hour,label:`${String(hour).padStart(2,"0")}:00`,orders:0,revenue:0}));for(const order of orders){const row=rows[new Date(order.created_at).getHours()]!;row.orders+=1;row.revenue+=Number(order.total)}return rows.filter(r=>r.orders>0)}
function buildPayments(orders:OrderRow[]):PaymentRow[]{return group(orders,row=>row.payment_status).map(row=>({name:row.name,count:row.count,value:orders.filter(order=>order.payment_status===row.name).reduce((s,r)=>s+Number(r.total),0)}))}
function group<T>(rows:T[],key:(row:T)=>string){const map=new Map<string,number>();for(const row of rows){const name=key(row);map.set(name,(map.get(name)??0)+1)}return Array.from(map,([name,count])=>({name,count}))}
function Kpis({items}:{items:Array<{label:string;value:string;icon:React.ReactNode}>}){return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(item=><article key={item.label} className="qs-stat flex min-h-[116px] items-center gap-4 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-orange-500/10 text-[#e85d2a] [&>svg]:size-5">{item.icon}</span><div className="min-w-0"><p className="text-[11px] font-semibold text-muted-foreground">{item.label}</p><strong className="mt-1 block truncate font-display text-xl tracking-[-.035em]">{item.value}</strong></div></article>)}</section>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <section className="qs-card p-4 sm:p-5"><h2 className="mb-4 text-sm font-bold">{title}</h2><div className="h-[300px]">{children}</div></section>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="qs-card overflow-hidden"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><span className="grid size-8 place-items-center rounded-lg bg-muted text-muted-foreground"><FileText className="size-4"/></span><h2 className="text-sm font-bold">{title}</h2></div>{children}</section>}
function Table({headers,rows,ar}:{headers:string[];rows:React.ReactNode[][];ar:boolean}){if(!rows.length)return <div className="grid min-h-[180px] place-items-center p-8 text-sm text-muted-foreground">{ar?"لا توجد بيانات فعلية كافية لهذا العرض بعد.":"Not enough real data for this detail yet."}</div>;return <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-separate border-spacing-0 text-xs"><thead className="sticky top-0 z-10 bg-muted/85 backdrop-blur"><tr>{headers.map(h=><th key={h} className="border-b border-border px-4 py-3 text-start text-[10px] font-bold uppercase tracking-[.08em] text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.map((cells,index)=><tr key={index} className="transition hover:bg-muted/30">{cells.map((cell,i)=><td key={i} className="border-b border-border/70 px-4 py-3.5 align-middle">{cell}</td>)}</tr>)}</tbody></table></div>}
function Status({value}:{value:string}){const n=value.toLowerCase();const positive=["paid","served","ready"].includes(n);const warning=["new","accepted","preparing","unpaid"].includes(n);return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${positive?"bg-emerald-500/10 text-emerald-600":warning?"bg-amber-500/10 text-amber-600":"bg-slate-500/10 text-slate-600"}`}>{value.replaceAll("_"," ")}</span>}
