import { useEffect, useRef, useState } from "react";
import type { RefObject } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Check, ChevronLeft, ChevronRight, FileText, Loader2, MousePointer2, Percent, Plus, Save, Settings2, Upload, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useRestaurant } from "@/hooks/useSuperAdmin";
import { humanError } from "@/lib/errors";
import { logAudit } from "@/lib/audit";
import { extractPdfVisualProducts } from "@/lib/pdf-menu-vision.server";
import { analyzePdfFile, fetchPdfBytes, openPdf, renderPdfPage, type PdfMenuAnalysis } from "@/lib/pdf-menu";
import { extractPdfTextForArea } from "@/lib/pdf-menu-selection";
import { MAX_PDF_BYTES, uploadRestaurantPdf } from "@/lib/storage";

type Product={name_en:string;name_ar:string;description_en:string|null;description_ar:string|null;price:number|null;currency:string|null;confidence:number};
type Item={id:string;page:number;x:number;y:number;width:number;height:number;product:Product;saved:boolean};
type Rect={x:number;y:number;width:number;height:number};
type Doc={id:string;file_url:string;file_parts:string[];file_name:string;page_count:number;is_active:boolean};
const blank:Product={name_en:"",name_ar:"",description_en:null,description_ar:null,price:null,currency:null,confidence:0};

export function ManualPdfMenuManager({restaurantId}:{restaurantId:string}){
 const {data:restaurant}=useRestaurant(restaurantId),qc=useQueryClient(),runVision=useServerFn(extractPdfVisualProducts),inputRef=useRef<HTMLInputElement>(null),canvasRef=useRef<HTMLCanvasElement>(null);
 const existing=useQuery<Doc|null>({queryKey:["platform","pdf-document",restaurantId],queryFn:async()=>{const {data,error}=await(supabase as any).from("menu_pdf_documents").select("id,file_url,file_parts,file_name,page_count,is_active").eq("restaurant_id",restaurantId).maybeSingle();if(error)throw error;return data?{...data,file_parts:Array.isArray(data.file_parts)?data.file_parts.filter((x:unknown):x is string=>typeof x==="string"):[]}:null;}});
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState<string|null>(null),[parts,setParts]=useState<string[]>([]),[analysis,setAnalysis]=useState<PdfMenuAnalysis>({page_count:0,pages:[],candidates:[]}),[page,setPage]=useState(1),[selecting,setSelecting]=useState(false),[rect,setRect]=useState<Rect|null>(null),[items,setItems]=useState<Item[]>([]),[active,setActive]=useState<string|null>(null),[reading,setReading]=useState(false),[busy,setBusy]=useState(false),[tax,setTax]=useState("0"),[service,setService]=useState("0"),[serviceOn,setServiceOn]=useState(false),[chargesDirty,setChargesDirty]=useState(false);
 useEffect(()=>{if(existing.data&&!file){setUrl(existing.data.file_url);setParts(existing.data.file_parts);setPage(1)}},[existing.data,file]);
 useEffect(()=>{if(restaurant){setTax(String(Number(restaurant.tax_rate??0)));setService(String(Number(restaurant.service_charge??0)))}},[restaurant]);
 useEffect(()=>{let off=false;void supabase.from("restaurant_settings").select("enable_service_charge").eq("restaurant_id",restaurantId).maybeSingle().then(({data})=>{if(!off&&data)setServiceOn(Boolean(data.enable_service_charge))});return()=>{off=true}},[restaurantId]);
 useEffect(()=>{let off=false;async function draw(){if(!canvasRef.current||!url||!analysis.page_count)return;try{const pdf=await openPdf(await fetchPdfBytes(url,parts));if(!off)await renderPdfPage(pdf,page,canvasRef.current,1800)}catch(e){if(!off)toast.error(humanError(e))}}void draw();return()=>{off=true}},[url,parts,page,analysis.page_count]);
 async function upload(next?:File){if(!next)return;if(next.type!=="application/pdf"&&!next.name.toLowerCase().endsWith(".pdf"))return void toast.error("Please upload a PDF menu.");if(next.size>MAX_PDF_BYTES)return void toast.error("PDF is too large. Maximum allowed size is 100 MB.");setBusy(true);try{const {analysis:a}=await analyzePdfFile(next),u=await uploadRestaurantPdf(restaurantId,next);setFile(next);setUrl(u.url);setParts(u.parts);setAnalysis(a);setItems([]);setActive(null);setPage(1);setSelecting(true);toast.success(`${a.page_count} page${a.page_count===1?"":"s"} ready. Select your first product.`)}catch(e){toast.error(humanError(e))}finally{setBusy(false);if(inputRef.current)inputRef.current.value=""}}
 async function read(r:Rect){if(!canvasRef.current||!url)return;setReading(true);const id=`manual-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;try{const image=crop(canvasRef.current,r),bytes=await fetchPdfBytes(url,parts),text=await extractPdfTextForArea(bytes,page,r),result=await runVision({data:{restaurantId,pageNumber:page,pageWidth:analysis.pages.find(p=>p.page_number===page)?.width??canvasRef.current.width,pageHeight:analysis.pages.find(p=>p.page_number===page)?.height??canvasRef.current.height,imageDataUrl:image,selectionOnly:true,selectedText:text}}),v=result.products?.[0]?.product,p:Product=v?{name_en:v.name_en??"",name_ar:v.name_ar??"",description_en:v.description_en??null,description_ar:v.description_ar??null,price:v.price==null?null:Number(v.price),currency:v.currency??null,confidence:Number(v.confidence??0)}:{...blank};setItems(x=>[...x,{id,page,...r,product:p,saved:false}]);setActive(id);setSelecting(false);if(!p.name_en&&!p.name_ar)toast.error("I could not reliably read this area. Select the complete product, including its title and price.");else toast.success("Product title, description and price detected in English and Arabic.")}catch(e){toast.error(`Could not read this product: ${humanError(e)}`)}finally{setReading(false)}}
 function edit(id:string,p:Partial<Product>){setItems(x=>x.map(i=>i.id===id?{...i,product:{...i.product,...p}}:i))}
 function saveItem(id:string){const i=items.find(x=>x.id===id);if(!i)return;if(!i.product.name_en&&!i.product.name_ar)return void toast.error("Add a product name before saving.");setItems(x=>x.map(a=>a.id===id?{...a,saved:true}:a));setActive(null);setSelecting(true);toast.success("Saved. Select the next product.")}
 async function saveCharges(){setBusy(true);try{const t=Math.max(0,Number(tax)||0),s=Math.max(0,Number(service)||0);const r=await supabase.from("restaurants").update({tax_rate:t,service_charge:s}).eq("id",restaurantId);if(r.error)throw r.error;const q=await supabase.from("restaurant_settings").upsert({restaurant_id:restaurantId,enable_service_charge:serviceOn},{onConflict:"restaurant_id"});if(q.error)throw q.error;setChargesDirty(false);await qc.invalidateQueries({queryKey:["platform","restaurant",restaurantId]});toast.success("Tax and service charge saved.")}catch(e){toast.error(humanError(e))}finally{setBusy(false)}}
 async function publish(){const saved=items.filter(i=>i.saved&&(i.product.name_en||i.product.name_ar));if(!url||!analysis.page_count||!saved.length)return void toast.error("Select and save at least one product first.");setBusy(true);try{const payload={restaurant_id:restaurantId,file_url:url,file_parts:parts,file_name:file?.name??existing.data?.file_name??"menu.pdf",page_count:analysis.page_count,analysis:{page_count:analysis.page_count,pages:analysis.pages,candidates:[]},is_active:true};let documentId=existing.data?.id;if(documentId){const {error}=await(supabase as any).from("menu_pdf_documents").update(payload).eq("id",documentId).eq("restaurant_id",restaurantId);if(error)throw error}else{const {data,error}=await(supabase as any).from("menu_pdf_documents").upsert(payload,{onConflict:"restaurant_id"}).select("id").single();if(error)throw error;documentId=data.id}await(supabase as any).from("menu_pdf_item_links").update({is_active:false}).eq("document_id",documentId).eq("restaurant_id",restaurantId).eq("is_active",true);const rows:any[]=[];for(const i of saved){const p=i.product,nameEn=p.name_en.trim()||p.name_ar.trim(),nameAr=p.name_ar.trim()||p.name_en.trim();const {data,error}=await supabase.from("menu_items").insert({restaurant_id:restaurantId,name_en:nameEn,name_ar:nameAr,description_en:p.description_en?.trim()||null,description_ar:p.description_ar?.trim()||null,price:p.price==null?0:p.price,is_available:true}).select("id").single();if(error)throw error;rows.push({document_id:documentId,restaurant_id:restaurantId,menu_item_id:data.id,candidate_id:i.id,page_number:i.page,x:i.x,y:i.y,width:i.width,height:i.height,label:`${nameEn} / ${nameAr}`,source:"manual-selection-ai",is_active:true})}const {error:linkError}=await(supabase as any).from("menu_pdf_item_links").insert(rows);if(linkError)throw linkError;await logAudit("menu.pdf_published",{restaurantId,entity:"menu_pdf_documents",entityId:documentId,metadata:{links:rows.length,pages:analysis.page_count,manualSelection:true,aiRead:true}});await qc.invalidateQueries({queryKey:["platform","pdf-document",restaurantId]});toast.success(`${rows.length} clickable products published.`)}catch(e){toast.error(humanError(e))}finally{setBusy(false)}}
 if(existing.isPending&&!url)return <div className="space-y-4"><Skeleton className="h-28 rounded-3xl"/><Skeleton className="h-[650px] rounded-3xl"/></div>;
 const saved=items.filter(i=>i.saved).length;
 return <div className="space-y-5 pb-10"><header className="rounded-[30px] border bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex gap-2"><Badge>Manual selection</Badge><Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50">AI auto-fill</Badge></div><h1 className="mt-2 text-2xl font-black">Interactive PDF Menu</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Select one complete product area. QuickServe reads the image and PDF text together and automatically fills English + Arabic title, description and price.</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy||reading} onClick={()=>inputRef.current?.click()}><Upload className="size-4"/>{url?"Replace PDF":"Upload PDF"}</Button><Button disabled={busy||reading||!saved} onClick={()=>void publish()}><Zap className="size-4"/>Publish · {saved}</Button></div><input ref={inputRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/></div></header>
 <section className="rounded-[30px] border bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Settings2 className="size-5"/></div><div><h2 className="font-bold">Whole-menu tax & service</h2><p className="text-xs text-muted-foreground">Applied automatically to the complete customer order.</p></div></div><div className="flex flex-wrap items-end gap-3"><Charge label="Tax %" value={tax} set={v=>{setTax(v);setChargesDirty(true)}}/><Charge label="Service %" value={service} set={v=>{setService(v);setChargesDirty(true)}}/><div className="flex items-center gap-2 rounded-xl border px-3 py-2.5"><Switch checked={serviceOn} onCheckedChange={v=>{setServiceOn(v);setChargesDirty(true)}}/><span className="text-sm font-semibold">Service enabled</span></div><Button disabled={!chargesDirty||busy} onClick={()=>void saveCharges()}><Save className="size-4"/>Save</Button></div></div></section>
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><section className="overflow-hidden rounded-[30px] border bg-card shadow-sm"><div className="flex items-center justify-between border-b p-4"><div><div className="flex items-center gap-2"><FileText className="size-5 text-primary"/><b>Original PDF</b></div><p className="mt-1 text-xs text-muted-foreground">Page {page} / {analysis.page_count||0}</p></div><div className="flex gap-1"><Button size="icon" variant="outline" disabled={page<=1} onClick={()=>setPage(v=>v-1)}><ChevronLeft className="size-4"/></Button><Button size="icon" variant="outline" disabled={page>=analysis.page_count} onClick={()=>setPage(v=>v+1)}><ChevronRight className="size-4"/></Button></div></div>{!url?<button onClick={()=>inputRef.current?.click()} className="m-4 grid min-h-[620px] w-[calc(100%-2rem)] place-items-center rounded-3xl border-2 border-dashed bg-muted/20"><span><Upload className="mx-auto size-10 text-muted-foreground"/><b className="mt-3 block">Upload original PDF</b></span></button>:<Selector canvasRef={canvasRef} selecting={selecting} rect={rect} setRect={setRect} onComplete={r=>void read(r)} reading={reading}/>} {url?<div className="flex items-center justify-between border-t bg-muted/20 p-4"><span className="flex items-center gap-2 text-xs text-muted-foreground"><MousePointer2 className="size-4"/>{selecting?"Drag around one complete product, including title and price":"Select a product area to start"}</span><Button variant={selecting?"default":"outline"} onClick={()=>setSelecting(v=>!v)} disabled={busy||reading}>{selecting?"Cancel":"Select product area"}</Button></div>:null}</section>
 <aside className="rounded-[30px] border bg-card shadow-sm"><div className="border-b p-4"><div className="flex justify-between"><div><b>Selected products</b><p className="mt-1 text-xs text-muted-foreground">{saved} saved · {items.length} selected</p></div><Badge>{reading?"Reading…":selecting?"Ready":"Review"}</Badge></div></div><div className="max-h-[760px] space-y-3 overflow-y-auto p-3">{reading?<div className="rounded-2xl border bg-primary/5 p-5 text-center"><Loader2 className="mx-auto animate-spin"/><b className="mt-2 block">Reading automatically…</b><p className="mt-1 text-xs text-muted-foreground">Image + PDF text + bilingual recovery</p></div>:null}{!items.length&&!reading?<div className="rounded-2xl border border-dashed p-7 text-center"><MousePointer2 className="mx-auto size-8 text-muted-foreground"/><b className="mt-3 block">Select your first product</b><Button className="mt-4" onClick={()=>setSelecting(true)}><Plus className="size-4"/>Select area</Button></div>:null}{items.map((i,n)=><Editor key={i.id} item={i} n={n+1} active={active===i.id} open={()=>setActive(i.id)} edit={p=>edit(i.id,p)} save={()=>saveItem(i.id)} remove={()=>{setItems(x=>x.filter(a=>a.id!==i.id));setActive(null)}}/> )}</div></aside></div></div>
}
function Charge({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <div><Label className="text-xs">{label}</Label><div className="relative mt-1"><Input type="number" min="0" max="100" step="0.01" value={value} onChange={e=>set(e.target.value)} className="pr-8"/><Percent className="absolute right-2.5 top-2.5 size-4 text-muted-foreground"/></div></div>}
function Editor({item,n,active,open,edit,save,remove}:{item:Item;n:number;active:boolean;open:()=>void;edit:(p:Partial<Product>)=>void;save:()=>void;remove:()=>void}){const p=item.product;return <div className={`rounded-2xl border ${item.saved?"border-emerald-200 bg-emerald-50/40":""}`}><button className="flex w-full items-center gap-3 p-3 text-left" onClick={open}><span className="grid size-8 place-items-center rounded-xl bg-muted text-xs font-bold">{n}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name_en||p.name_ar||"Product"}</b><span className="text-xs text-muted-foreground">{p.price==null?"Price missing":`${p.price} ${p.currency||""}`} · P{item.page}</span></span>{item.saved?<Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50"><Check className="mr-1 size-3"/>Saved</Badge>:<Badge variant="outline">Review</Badge>}</button>{active?<div className="space-y-3 border-t p-3"><div className="grid gap-2 sm:grid-cols-2"><Field label="Product title (English)" value={p.name_en} set={v=>edit({name_en:v})}/><Field label="اسم المنتج (العربية)" value={p.name_ar} set={v=>edit({name_ar:v})}/></div><div className="grid gap-2 sm:grid-cols-[1fr_100px]"><Field label="Price" value={p.price==null?"":String(p.price)} type="number" set={v=>edit({price:v===""?null:Number(v)})}/><Field label="Currency" value={p.currency||""} set={v=>edit({currency:v})}/></div><div><Label className="text-xs">Description (English)</Label><Textarea className="mt-1" value={p.description_en||""} onChange={e=>edit({description_en:e.target.value||null})}/></div><div><Label className="text-xs">الوصف (العربية)</Label><Textarea dir="rtl" className="mt-1" value={p.description_ar||""} onChange={e=>edit({description_ar:e.target.value||null})}/></div><div className="flex justify-between"><Button variant="ghost" size="sm" onClick={remove}><X className="size-4"/>Remove</Button><Button size="sm" onClick={save}><Check className="size-4"/>Save & select next</Button></div></div>:null}</div>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:"text"|"number"}){return <div><Label className="text-xs">{label}</Label><Input className="mt-1" type={type} value={value} onChange={e=>set(e.target.value)}/></div>}
function crop(source:HTMLCanvasElement,r:Rect){const pad=.06,sx=Math.max(0,(r.x-pad)*source.width),sy=Math.max(0,(r.y-pad)*source.height),ex=Math.min(source.width,(r.x+r.width+pad)*source.width),ey=Math.min(source.height,(r.y+r.height+pad)*source.height),sw=ex-sx,sh=ey-sy,scale=Math.min(3,Math.max(1,1600/sw)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(sw*scale));c.height=Math.max(1,Math.round(sh*scale));const ctx=c.getContext("2d");if(!ctx)throw new Error("Could not prepare selected image");ctx.imageSmoothingQuality="high";ctx.drawImage(source,sx,sy,sw,sh,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.94)}
function Selector({canvasRef,selecting,rect,setRect,onComplete,reading}:{canvasRef:RefObject<HTMLCanvasElement|null>;selecting:boolean;rect:Rect|null;setRect:(r:Rect|null)=>void;onComplete:(r:Rect)=>void;reading:boolean}){const drag=useRef<{x:number;y:number;id:number}|null>(null);const point=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}};const down=(e:React.PointerEvent<HTMLDivElement>)=>{if(!selecting||reading||e.button!==0)return;const p=point(e);drag.current={...p,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);setRect({...p,width:0,height:0})};const move=(e:React.PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const p=point(e);setRect({x:Math.min(d.x,p.x),y:Math.min(d.y,p.y),width:Math.abs(p.x-d.x),height:Math.abs(p.y-d.y)})};const up=(e:React.PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;drag.current=null;const p=point(e),r={x:Math.min(d.x,p.x),y:Math.min(d.y,p.y),width:Math.abs(p.x-d.x),height:Math.abs(p.y-d.y)};setRect(null);if(r.width<.008||r.height<.008)return void toast.info("Select the complete product block.");onComplete(r)};return <div className={`relative mx-auto w-full max-w-5xl overflow-hidden bg-white ${selecting?"cursor-crosshair select-none":""}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null;setRect(null)}}><canvas ref={canvasRef} className="block h-auto w-full"/>{selecting?<div className="pointer-events-none absolute inset-0 bg-primary/[.025]"/>:null}{rect?<div className="pointer-events-none absolute rounded-lg border-2 border-primary bg-primary/15 shadow-[0_0_0_9999px_rgba(15,23,42,.18)]" style={{left:`${rect.x*100}%`,top:`${rect.y*100}%`,width:`${rect.width*100}%`,height:`${rect.height*100}%`}}/>:null}{selecting?<div className="pointer-events-none absolute left-1/2 top-4 -translate-x-1/2 rounded-full bg-background/95 px-4 py-2 text-xs font-bold shadow-lg">Drag around one complete product</div>:null}</div>}
