import { useMemo, useState } from "react";
import { Bell, CalendarDays, CheckCircle2, ChevronRight, Clock3, CreditCard, Grid2x2, Search, SlidersHorizontal, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { usePlatformOrders, useOrderItems, useRestaurant } from "@/hooks/useSuperAdmin";
import { useI18n } from "@/lib/i18n";
import { formatDateTime, formatMoney } from "@/lib/format";
import { cancelReasonLabel } from "@/lib/order-ops";
import { cn } from "@/lib/utils";

const FILTERS = [
  { id: "all", en: "All", ar: "الكل", icon: Grid2x2 }, { id: "open", en: "Open", ar: "مفتوحة", icon: Clock3 },
  { id: "ready", en: "Ready", ar: "جاهزة", icon: Bell }, { id: "served", en: "Served", ar: "مُقدَّمة", icon: CheckCircle2 },
  { id: "paid", en: "Paid", ar: "مدفوعة", icon: CreditCard }, { id: "cancelled", en: "Cancelled", ar: "ملغاة", icon: XCircle },
] as const;
const OPEN = ["new", "accepted", "preparing"];
const STATUS: Record<string,string> = { new:"bg-amber-50 text-amber-700", accepted:"bg-blue-50 text-blue-700", preparing:"bg-orange-50 text-orange-700", ready:"bg-emerald-50 text-emerald-700", served:"bg-slate-100 text-slate-700", paid:"bg-violet-50 text-violet-700", cancelled:"bg-rose-50 text-rose-700" };

export function OrdersManager({ restaurantId }: { restaurantId: string }) {
  const { t, lang } = useI18n(); const [filter,setFilter]=useState<(typeof FILTERS)[number]["id"]>("all"); const [search,setSearch]=useState(""); const [open,setOpen]=useState<string|null>(null); const {data:restaurant}=useRestaurant(restaurantId); const orders=usePlatformOrders({restaurantId}); const currency=restaurant?.currency??"JOD";
  const rows=useMemo(()=>{const term=search.trim().toLowerCase();return (orders.data??[]).filter(o=>{const ok=filter==="all"?true:filter==="open"?OPEN.includes(o.status):o.status===filter;if(!ok)return false;return !term||o.order_number.toLowerCase().includes(term)||(o.table?.table_number??"").toLowerCase().includes(term);});},[orders.data,filter,search]);
  const counts=useMemo(()=>Object.fromEntries(FILTERS.map(f=>[f.id,(orders.data??[]).filter(o=>f.id==="all"?true:f.id==="open"?OPEN.includes(o.status):o.status===f.id).length])),[orders.data]);
  return <div className="space-y-5"><header><div className="flex items-end justify-between gap-3"><div><h1 className="text-[28px] font-bold tracking-[-0.04em]">{t("sa.orders.title")}</h1><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"إدارة جميع الطلبات والطاولات":"Manage all orders and tables"}</p></div><button className="grid size-12 place-items-center rounded-2xl border bg-card shadow-sm"><SlidersHorizontal className="size-5"/></button></div><div className="relative mt-5"><Search className="pointer-events-none absolute inset-y-0 start-4 my-auto size-5 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={lang==="ar"?"ابحث برقم الطلب أو الطاولة…":"Search order or table…"} className="h-13 rounded-2xl border bg-card ps-11 shadow-sm"/></div></header>
  <div className="no-scrollbar -mx-1 flex gap-2 overflow-x-auto px-1 pb-1">{FILTERS.map(f=>{const Icon=f.icon;return <button key={f.id} onClick={()=>setFilter(f.id)} className={cn("flex shrink-0 items-center gap-2 rounded-full border px-4 py-2.5 text-sm font-semibold transition",filter===f.id?"border-transparent bg-primary text-primary-foreground shadow-sm":"bg-card text-muted-foreground hover:text-foreground")}><Icon className="size-4"/>{lang==="ar"?f.ar:f.en}<span className={cn("rounded-full px-1.5 text-[10px]",filter===f.id?"bg-white/20":"bg-muted")}>{counts[f.id]??0}</span></button>})}</div>
  {orders.isPending?<div className="space-y-3">{[1,2,3,4].map(i=><Skeleton key={i} className="h-32 rounded-3xl"/>)}</div>:rows.length===0?<div className="panel rounded-3xl p-12 text-center text-sm text-muted-foreground">No orders found.</div>:<div className="space-y-3">{rows.map(o=><article key={o.id} className={cn("panel overflow-hidden rounded-3xl border-l-4",o.status==="cancelled"?"border-l-rose-400":"border-l-emerald-400")}><button className="flex w-full items-center gap-4 p-4 text-start sm:p-5" onClick={()=>setOpen(open===o.id?null:o.id)}><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-muted text-base font-bold">{o.table?.table_number??"—"}<span className="text-[9px] font-medium text-muted-foreground">TABLE</span></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><b className="text-base tabular-nums">{o.order_number}</b><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-bold uppercase",STATUS[o.status]??"bg-muted")}>{o.status}</span></span><span className="mt-1 flex flex-wrap gap-2 text-xs text-muted-foreground"><span><CalendarDays className="mr-1 inline size-3.5"/>{formatDateTime(o.created_at,lang)}</span><span>• {o.payment_status}</span>{o.status==="cancelled"&&<span>• {cancelReasonLabel(o.cancellation_reason,lang==="ar")}</span>}</span></span><span className="flex items-center gap-2"><span className="text-lg font-bold tabular-nums">{formatMoney(o.total,currency,lang)}</span><ChevronRight className={cn("size-5 text-muted-foreground transition-transform",open===o.id&&"rotate-90")}/></span></button>{open===o.id&&<OrderDetail orderId={o.id} currency={currency}/>}</article>)}</div>}</div>;
}
function OrderDetail({orderId,currency}:{orderId:string;currency:string}){const{lang}=useI18n();const items=useOrderItems(orderId);return <div className="border-t bg-muted/25 px-5 py-4">{items.isPending?<Skeleton className="h-12"/>:<ul className="space-y-3">{(items.data??[]).map(item=><li key={item.id} className="flex items-center gap-3 text-sm"><Badge variant="secondary">×{item.quantity}</Badge><span className="min-w-0 flex-1 truncate">{lang==="ar"?item.product_name_snapshot_ar||item.product_name_snapshot_en:item.product_name_snapshot_en||item.product_name_snapshot_ar}</span><span className="font-semibold">{formatMoney(item.total_price,currency,lang)}</span></li>)}</ul>}</div>}
