import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { IdCard, KeyRound, MoreVertical, Pencil, Plus, Search, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { SeatUsage } from "@/components/manage/SeatUsage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { humanError } from "@/lib/errors";
import { logAudit } from "@/lib/audit";
import { ACCESS_LEVEL_LABELS, accessLevelFor, ROLE_LABELS, type AppRole } from "@/lib/permissions";
import { inviteStaffMember, listStaffLogins, removeStaffMember, resetStaffPassword } from "@/lib/staff.functions";
import { formatDate } from "@/lib/format";
import { getStaffAccess, issueStaffAccess } from "@/lib/staff-auth.functions";
import { qrDataUrl } from "@/lib/qr";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const ROLES: AppRole[] = ["restaurant_admin", "manager", "kitchen", "waiter", "cashier"];
export function StaffManager({restaurantId}:{restaurantId:string}){
 const{t,lang}=useI18n();const qc=useQueryClient();const invite=useServerFn(inviteStaffMember);const reset=useServerFn(resetStaffPassword);const remove=useServerFn(removeStaffMember);const readLogins=useServerFn(listStaffLogins);const readAccess=useServerFn(getStaffAccess);const issueAccess=useServerFn(issueStaffAccess);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[search,setSearch]=useState("");const[credentials,setCredentials]=useState<any>(null);const[editing,setEditing]=useState<any>(null);const[pending,setPending]=useState<any>(null);const[access,setAccess]=useState<any>(null);const[badge,setBadge]=useState<string|null>(null);
 const staff=useQuery({queryKey:["platform","staff",restaurantId],queryFn:async()=>{const{data,error}=await supabase.from("staff").select("*").eq("restaurant_id",restaurantId).order("created_at",{ascending:false});if(error)throw error;return data??[];}});const logins=useQuery({queryKey:["platform","staff-logins",restaurantId],queryFn:()=>readLogins({data:{restaurantId}})});const rows=(staff.data??[]).filter(x=>{const q=search.toLowerCase();return !q||`${x.name} ${x.email??""}`.toLowerCase().includes(q)});
 async function refresh(){await qc.invalidateQueries({queryKey:["platform"]});}async function create(){setBusy(true);try{const r=await invite({data:{restaurantId,email:form.email.trim(),name:form.name.trim(),role:form.role}});setCredentials(r);setOpen(false);setForm({name:"",email:"",role:"waiter"});await refresh();toast.success(t("sa.staff.invited"));}catch(e){toast.error(humanError(e,lang));}finally{setBusy(false);}}async function password(id:string,name:string){try{const r=await reset({data:{staffId:id}});setCredentials({name,email:r.email,password:r.password});}catch(e){toast.error(humanError(e,lang));}}async function del(id:string,name:string){try{await remove({data:{staffId:id}});await refresh();setPending(null);toast.success(t("sa.staff.deleted"));}catch(e){toast.error(humanError(e,lang));}}async function openAccess(id:string){try{const r=await readAccess({data:{staffId:id}});setAccess(r);setBadge(await qrDataUrl(`${location.origin}/staff/badge/${r.badgeCode}`,420));}catch(e){toast.error(humanError(e,lang));}}
 const[form,setForm]=useState({name:"",email:"",role:"waiter" as AppRole});
 return <div className="space-y-5"><header><div className="flex items-end justify-between gap-3"><div><h1 className="text-[28px] font-bold tracking-[-0.04em]">{t("sa.staff.title")}</h1><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"إدارة فريقك وصلاحيات الوصول":"Manage your team and access"}</p></div><Button onClick={()=>setOpen(true)}><Plus className="size-4"/>{t("sa.staff.new")}</Button></div></header><SeatUsage restaurantId={restaurantId}/><div className="relative"><Search className="absolute start-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={lang==="ar"?"ابحث عن موظف…":"Search staff…"} className="h-12 rounded-2xl bg-card ps-10"/></div>
 {staff.isPending?<Skeleton className="h-64 rounded-3xl"/>:<div className="space-y-3">{rows.map((m,i)=><article key={m.id} className="panel rounded-3xl p-4 sm:p-5"><div className="flex items-center gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-amber-50 text-amber-900"><UserRound className="size-6"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{m.name}</h2><Badge variant="outline">{ACCESS_LEVEL_LABELS[accessLevelFor(m.role)][lang]}</Badge><Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50">{m.is_active?t("common.active"):t("common.inactive")}</Badge></div><p className="mt-1 truncate text-sm text-muted-foreground">{m.email??"—"}</p><p className="mt-1 text-xs text-muted-foreground">{ROLE_LABELS[m.role][lang]} · {formatDate(m.created_at,lang)}</p></div><button className="grid size-9 place-items-center rounded-xl hover:bg-muted"><MoreVertical className="size-5"/></button></div><div className="mt-4 grid grid-cols-2 gap-2 border-t pt-4 sm:grid-cols-4"><Button size="sm" variant="outline" onClick={()=>setEditing(m)}><Pencil className="size-4"/>Edit</Button><Button size="sm" variant="outline" onClick={()=>void password(m.id,m.name)}><KeyRound className="size-4"/>Reset</Button><Button size="sm" variant="outline" onClick={()=>void openAccess(m.id)}><IdCard className="size-4"/>Access</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>setPending(m)}><Trash2 className="size-4"/>Delete</Button></div></article>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{t("sa.staff.new")}</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Email</Label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Role</Label><Select value={form.role} onValueChange={v=>setForm({...form,role:v as AppRole})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ROLES.map(r=><SelectItem key={r} value={r}>{ROLE_LABELS[r][lang]}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="ghost" onClick={()=>setOpen(false)}>{t("common.cancel")}</Button><Button disabled={busy} onClick={()=>void create()}>{t("common.create")}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!credentials} onOpenChange={o=>!o&&setCredentials(null)}><DialogContent><DialogHeader><DialogTitle>{lang==="ar"?"بيانات الدخول":"Login credentials"}</DialogTitle><DialogDescription>{credentials?.email}</DialogDescription></DialogHeader><div className="rounded-2xl bg-muted p-4 font-mono text-sm">{credentials?.password??"Password unchanged"}</div><DialogFooter><Button onClick={()=>setCredentials(null)}>{t("common.close")}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!pending} onOpenChange={o=>!o&&setPending(null)}><DialogContent><DialogHeader><DialogTitle>{lang==="ar"?"حذف الموظف؟":"Delete staff member?"}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{pending?.name}</p><DialogFooter><Button variant="ghost" onClick={()=>setPending(null)}>{t("common.cancel")}</Button><Button variant="destructive" onClick={()=>void del(pending.id,pending.name)}>{t("common.delete")}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!access} onOpenChange={o=>!o&&setAccess(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Staff access</DialogTitle></DialogHeader>{badge&&<img src={badge} alt="Staff badge" className="mx-auto size-56"/>}<p className="text-center text-sm text-muted-foreground">{access?.name}</p><DialogFooter><Button onClick={()=>setAccess(null)}>{t("common.close")}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
