import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Copy, ExternalLink, Layers3, MoreVertical, Plus, Printer, QrCode, RefreshCw, Table2, Power } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { useRestaurant } from "@/hooks/useSuperAdmin";
import { useI18n } from "@/lib/i18n";
import { humanError } from "@/lib/errors";
import { logAudit } from "@/lib/audit";
import { downloadDataUrl, printQrCards, qrDataUrl, tableMenuUrl } from "@/lib/qr";

export function TablesManager({ restaurantId }: { restaurantId: string }) {
 const {t,lang}=useI18n(); const qc=useQueryClient(); const {data:restaurant}=useRestaurant(restaurantId); const [dialog,setDialog]=useState<"single"|"bulk"|null>(null); const [number,setNumber]=useState(""); const [name,setName]=useState(""); const [count,setCount]=useState("5"); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState<{label:string;dataUrl:string}|null>(null);
 const tables=useQuery({queryKey:["platform","tables",restaurantId],queryFn:async()=>{const {data,error}=await supabase.from("restaurant_tables").select("*").eq("restaurant_id",restaurantId).order("table_number",{ascending:true});if(error)throw error;return data??[];}});
 async function refresh(){await qc.invalidateQueries({queryKey:["platform","tables",restaurantId]});}
 async function create(rows:{table_number:string;table_name:string|null}[]){setBusy(true);try{const{error}=await supabase.from("restaurant_tables").insert(rows.map(r=>({...r,restaurant_id:restaurantId,qr_token:crypto.randomUUID().replace(/-/g,"")})));if(error)throw error;await logAudit("table.created",{restaurantId,entity:"restaurant_tables",metadata:{count:rows.length}});await refresh();toast.success(t("common.saved"));setDialog(null);setNumber("");setName("");}catch(e){toast.error(humanError(e,lang));}finally{setBusy(false);}}
 async function toggle(id:string,active:boolean){try{const{error}=await supabase.from("restaurant_tables").update({is_active:!active}).eq("id",id);if(error)throw error;await refresh();}catch(e){toast.error(humanError(e,lang));}}
 async function regenerate(id:string){try{const{error}=await supabase.from("restaurant_tables").update({qr_token:crypto.randomUUID().replace(/-/g,""),qr_code_url:null}).eq("id",id);if(error)throw error;await refresh();toast.success(t("common.saved"));}catch(e){toast.error(humanError(e,lang));}}
 async function showQr(tb:any){if(!restaurant)return;setPreview({label:`${t("sa.tables.number")} ${tb.table_number}`,dataUrl:await qrDataUrl(tableMenuUrl(restaurant.slug,tb.qr_token))});}
 async function printAll(){if(!restaurant)return;const rows=(tables.data??[]).filter(x=>x.is_active);if(!rows.length)return;await printQrCards(restaurant.name,t("sa.tables.scan"),rows.map(x=>({table_number:x.table_number,table_name:x.table_name,url:tableMenuUrl(restaurant.slug,x.qr_token)})),{back:lang==="ar"?"← رجوع":"← Back",print:lang==="ar"?"طباعة":"Print"});}
 const next=(tables.data??[]).length+1; const active=(tables.data??[]).filter(x=>x.is_active).length;
 return <div className="space-y-5"><header><div className="flex items-end justify-between gap-3"><div><h1 className="text-[28px] font-bold tracking-[-0.04em]">{t("sa.tables.title")}</h1><p className="mt-1 text-sm text-muted-foreground">{lang==="ar"?"إدارة الطاولات ورموز QR الخاصة بمطعمك":"Manage your tables and their QR codes"}</p></div><div className="flex gap-2"><Button variant="outline" className="hidden sm:flex" onClick={()=>void printAll()}><Printer className="size-4"/> {t("sa.tables.print")}</Button><Button variant="outline" onClick={()=>setDialog("bulk")}><Layers3 className="size-4"/><span className="hidden sm:inline">{t("sa.tables.bulk")}</span></Button><Button onClick={()=>setDialog("single")}><Plus className="size-4"/>{t("sa.tables.new")}</Button></div></div><div className="mt-4 flex gap-2 text-xs"><Badge variant="secondary">{tables.data?.length??0} {lang==="ar"?"طاولة":"tables"}</Badge><Badge variant="secondary">{active} {lang==="ar"?"نشطة":"active"}</Badge></div></header>
 {tables.isPending?<div className="space-y-3">{[1,2,3].map(i=><Skeleton key={i} className="h-36 rounded-3xl"/>)}</div>:<div className="space-y-3">{(tables.data??[]).map(tb=><article key={tb.id} className="panel rounded-3xl p-4 sm:p-5"><div className="flex items-center gap-4"><div className="relative"><div className="grid size-16 place-items-center rounded-2xl bg-amber-50 text-amber-900"><Table2 className="size-8"/></div><span className="absolute -bottom-2 -end-2 rounded-lg bg-primary px-2 py-1 text-xs font-bold text-primary-foreground">{String(tb.table_number).padStart(2,"0")}</span></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-base font-bold">{lang==="ar"?`الطاولة ${tb.table_number}`:`Table number ${tb.table_number}`}</h2><Badge className="rounded-full bg-emerald-50 text-emerald-700 hover:bg-emerald-50"><span className="mr-1.5 size-1.5 rounded-full bg-emerald-500"/>{tb.is_active?t("common.active"):t("common.inactive")}</Badge></div><p className="mt-1 truncate text-sm text-muted-foreground">{tb.table_name??"—"}</p><p className="mt-1 text-xs text-muted-foreground">{lang==="ar"?"رمز QR مرتبط بهذه الطاولة":"QR code linked to this table"}</p></div><button className="grid size-9 place-items-center rounded-xl hover:bg-muted"><MoreVertical className="size-5"/></button></div><div className="mt-5 flex flex-wrap gap-2 border-t pt-4"><Button size="sm" variant="outline" onClick={()=>void showQr(tb)}><QrCode className="size-4"/> QR</Button><Button size="sm" variant="outline" onClick={()=>void regenerate(tb.id)}><RefreshCw className="size-4"/>{t("sa.tables.regenerate")}</Button><Button size="sm" variant="outline" onClick={()=>void toggle(tb.id,tb.is_active)}><Power className="size-4"/>{tb.is_active?t("sa.staff.deactivate"):t("sa.staff.reactivate")}</Button></div></article>)}</div>}
 <Dialog open={dialog!==null} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog==="bulk"?t("sa.tables.bulk"):t("sa.tables.new")}</DialogTitle><DialogDescription>{t("sa.tables.title")}</DialogDescription></DialogHeader>{dialog==="bulk"?<div className="space-y-2"><Label>{t("sa.wizard.tableCount")}</Label><Input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></div>:<div className="space-y-3"><div><Label>{t("sa.tables.number")}</Label><Input value={number} placeholder={String(next)} onChange={e=>setNumber(e.target.value)}/></div><div><Label>{t("sa.tables.name")}</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div></div>}<DialogFooter><Button variant="ghost" onClick={()=>setDialog(null)}>{t("common.cancel")}</Button><Button disabled={busy} onClick={()=>dialog==="bulk"?void create(Array.from({length:Math.min(Math.max(Number(count)||1,1),100)},(_,i)=>({table_number:String(next+i),table_name:null}))):void create([{table_number:number.trim()||String(next),table_name:name.trim()||null}])}>{t("common.create")}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={preview!==null} onOpenChange={o=>!o&&setPreview(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>{preview?.label}</DialogTitle><DialogDescription>{t("sa.tables.scan")}</DialogDescription></DialogHeader>{preview&&<img src={preview.dataUrl} alt={preview.label} className="mx-auto size-56"/>}<DialogFooter>{preview&&<Button variant="outline" onClick={()=>downloadDataUrl(preview.dataUrl,`${preview.label}.png`)}>Download</Button>}<Button onClick={()=>setPreview(null)}>{t("common.close")}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
