import { useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BrainCircuit, Camera, Check, FileImage, Layers3, Sparkles, Wand2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { DEFAULT_THEME, parseMenuTheme, type MenuTheme } from "@/lib/menu-theme";
import { orchestrateSmartMenuDesign } from "@/lib/smart-menu-orchestrator.server";
import { refineSmartMenuElement } from "@/lib/menu-element-intelligence.server";
import { cn } from "@/lib/utils";

type Mode = "new" | "reference";
type ElementId = "hero" | "typography" | "category" | "item-card" | "price" | "imagery" | "background" | "spacing";
const moods = [["Editorial","Magazine-led, confident and art-directed"],["Modern Levantine","Warm, cultural and contemporary"],["Quiet Luxury","Restrained, premium and tactile"],["Experimental","Unexpected composition and bold rhythm"],["Human Crafted","Print texture, imperfection and character"],["Photography First","Food imagery drives the composition"]] as const;
const elementLabels: Record<ElementId,string> = { hero:"Hero", typography:"Typography", category:"Category", "item-card":"Item card", price:"Prices", imagery:"Imagery", background:"Background", spacing:"Spacing" };

export function UnifiedMenuStudio({ restaurantId }: { restaurantId: string }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const queryClient = useQueryClient();
  const orchestrate = useServerFn(orchestrateSmartMenuDesign);
  const refine = useServerFn(refineSmartMenuElement);
  const [mode,setMode]=useState<Mode>("new"); const [brief,setBrief]=useState(""); const [references,setReferences]=useState<string[]>([]);
  const [mood,setMood]=useState("Editorial"); const [concepts,setConcepts]=useState<Array<{id:string;theme:string}>>([]); const [active,setActive]=useState(0);
  const [theme,setTheme]=useState<MenuTheme>(DEFAULT_THEME); const [selected,setSelected]=useState<ElementId>("hero"); const [instruction,setInstruction]=useState("");
  const [busy,setBusy]=useState(false); const [refining,setRefining]=useState(false); const [saving,setSaving]=useState(false);
  const restaurant=useQuery({queryKey:["unified-menu-studio",restaurantId],queryFn:async()=>{const {data,error}=await supabase.from("restaurants").select("id,name,menu_theme,currency").eq("id",restaurantId).single();if(error)throw error;return data;}});

  async function addFiles(files:FileList|null){if(!files)return;const encoded:string[]=[];for(const file of Array.from(files).slice(0,5-references.length)){if(!file.type.startsWith("image/"))continue;encoded.push(await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);}));}setReferences(old=>[...old,...encoded].slice(0,5));}
  async function design(){setBusy(true);try{const result=await orchestrate({data:{restaurantId,brief,references,direction:mood,language:"en"}});const next=result.concepts.map(c=>({id:c.id,theme:c.theme}));setConcepts(next);setActive(0);setTheme(next[0]?parseMenuTheme(JSON.parse(next[0].theme)):DEFAULT_THEME);toast.success("Creative director created 3 distinct directions");}catch(e){toast.error(e instanceof Error?e.message:"Could not create the menu");}finally{setBusy(false);}}
  function selectConcept(i:number){setActive(i);const c=concepts[i];if(c)setTheme(parseMenuTheme(JSON.parse(c.theme)));}
  async function refineElement(){if(!instruction.trim())return;setRefining(true);try{const result=await refine({data:{restaurantId,element:selected,instruction,currentTheme:JSON.stringify(theme)}});setTheme(parseMenuTheme(JSON.parse(result.theme)));toast.success(`${elementLabels[selected]} refined by AI`);}catch(e){toast.error(e instanceof Error?e.message:"Could not refine element");}finally{setRefining(false);}}
  async function save(){setSaving(true);try{const {error}=await supabase.from("restaurants").update({menu_theme:theme}).eq("id",restaurantId);if(error)throw error;await queryClient.invalidateQueries({queryKey:["unified-menu-studio",restaurantId]});toast.success("Menu saved");}catch(e){toast.error(e instanceof Error?e.message:"Could not save");}finally{setSaving(false);}}

  return <div className="min-h-[calc(100vh-7rem)] bg-[#f4f2ee] text-[#171717]"><div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6 lg:px-8">
    <header className="mb-5 rounded-[2rem] border bg-[#171717] p-6 text-white shadow-xl sm:p-8"><Badge className="border-white/20 bg-white/10 text-white">CREATIVE INTELLIGENCE</Badge><h1 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-5xl">A designer, not a template machine.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/60 sm:text-base">One creative brain combines editable structure, practical restaurant editing and professional image art direction. The companies stay behind the scenes.</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-semibold text-white/70">{["Understand","Art-direct","Compose","Humanize","Make editable","Quality-check"].map((s,i)=><span key={s} className="rounded-full border border-white/10 bg-white/[.06] px-3 py-2"><span className="mr-1 text-white/30">0{i+1}</span>{s}</span>)}</div></header>
    <div className="grid gap-5 lg:grid-cols-[370px_minmax(0,1fr)]"><aside className="space-y-4">
      <section className="rounded-[1.75rem] border bg-white p-5 shadow-sm"><div className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-black/40">Creative mode</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setMode("new")} className={cn("rounded-2xl border p-4 text-left",mode==="new"?"border-black bg-black text-white":"hover:border-black/30")}><Wand2 className="mb-7 size-5"/><div className="font-bold">New direction</div><p className="mt-1 text-xs opacity-55">Invent something original.</p></button><button onClick={()=>setMode("reference")} className={cn("rounded-2xl border p-4 text-left",mode==="reference"?"border-black bg-black text-white":"hover:border-black/30")}><FileImage className="mb-7 size-5"/><div className="font-bold">Use reference</div><p className="mt-1 text-xs opacity-55">Understand the visual DNA.</p></button></div></section>
      {mode==="reference"&&<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div className="text-xs font-bold uppercase tracking-[.18em] text-black/40">Visual DNA</div><span className="text-xs text-black/40">{references.length}/5</span></div><input ref={inputRef} type="file" accept="image/*" multiple className="hidden" onChange={e=>void addFiles(e.target.files)}/><button onClick={()=>inputRef.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-black/20 p-5 text-sm font-semibold"><FileImage className="size-5"/>Upload menu references</button>{references.length>0&&<div className="mt-3 grid grid-cols-3 gap-2">{references.map((src,i)=><div key={src.slice(-24)+i} className="relative aspect-[3/4] overflow-hidden rounded-xl"><img src={src} alt="Reference" className="h-full w-full object-cover"/><button onClick={()=>setReferences(old=>old.filter((_,n)=>n!==i))} className="absolute right-1 top-1 rounded-full bg-black/70 px-2 py-1 text-xs text-white">×</button></div>)}</div>}<p className="mt-3 text-xs leading-5 text-black/45">The AI extracts composition, hierarchy, typography, crop logic, spacing, material and rhythm, then rebuilds the system as editable design logic.</p></section>}
      <section className="rounded-[1.75rem] border bg-white p-5 shadow-sm"><div className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-black/40">Creative brief</div><Textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="e.g. premium Amman steakhouse, cinematic food photography, contemporary Arabic + English, unexpected editorial composition…" className="min-h-28 resize-none rounded-2xl"/><div className="mt-4 text-xs font-bold uppercase tracking-[.18em] text-black/40">Creative personality</div><div className="mt-2 grid grid-cols-2 gap-2">{moods.map(([name,desc])=><button key={name} onClick={()=>setMood(name)} className={cn("rounded-xl border p-3 text-left",mood===name?"border-black bg-black text-white":"hover:bg-black/[.025]")}><div className="text-xs font-bold">{name}</div><div className="mt-1 text-[10px] opacity-50">{desc}</div></button>)}</div><Button className="mt-4 w-full rounded-xl" onClick={design} disabled={busy}>{busy?<><Sparkles className="mr-2 size-4 animate-pulse"/>Creative director working…</>:<><Sparkles className="mr-2 size-4"/>Create my menu</>}</Button></section>
      <section className="rounded-[1.75rem] border bg-white p-5 shadow-sm"><div className="mb-3 flex items-center gap-2"><Layers3 className="size-4"/><div className="text-xs font-bold uppercase tracking-[.18em] text-black/40">Edit anything with AI</div></div><div className="grid grid-cols-2 gap-2">{(Object.keys(elementLabels) as ElementId[]).map(id=><button key={id} onClick={()=>setSelected(id)} className={cn("rounded-xl border px-3 py-2 text-left text-xs font-semibold",selected===id?"border-black bg-black text-white":"hover:bg-black/[.025]")}>{elementLabels[id]}</button>)}</div><Textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder={`Change the ${elementLabels[selected].toLowerCase()}…`} className="mt-3 min-h-20 resize-none rounded-xl"/><Button className="mt-3 w-full" onClick={refineElement} disabled={refining||!instruction.trim()}>{refining?<><Sparkles className="mr-2 size-4 animate-pulse"/>Refining…</>:<><Sparkles className="mr-2 size-4"/>Refine selected element</>}</Button><p className="mt-2 text-[10px] leading-4 text-black/40">The AI changes the selected element while preserving the rest of the composition.</p></section>
    </aside>
    <main className="rounded-[2rem] border bg-[#ddd9d2] p-3 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between rounded-2xl bg-white/80 p-3 backdrop-blur"><div><div className="text-sm font-bold">{restaurant.data?.name??"Restaurant"} — Creative Canvas</div><div className="text-xs text-black/40">Selected: {elementLabels[selected]}</div></div><Button onClick={save} disabled={saving}>{saving?"Saving…":"Save design"}</Button></div>
      <div className="mb-4 grid gap-2 sm:grid-cols-3">{concepts.map((c,i)=><button key={c.id} onClick={()=>selectConcept(i)} className={cn("rounded-2xl border bg-white p-3 text-left",active===i?"border-black ring-2 ring-black/10":"hover:border-black/30")}><div className="text-xs font-bold"><span className="mr-2 inline-grid size-6 place-items-center rounded-full bg-black text-white">{i+1}</span>Creative concept {i+1}</div><div className="mt-2 text-[11px] text-black/45">{i===0?"Balanced editorial direction":i===1?"Alternative composition":"Unexpected visual language"}</div></button>)}{!concepts.length&&<div className="sm:col-span-3 rounded-2xl border border-dashed border-black/15 bg-white/40 p-6 text-center text-sm text-black/40">Create a direction to activate the intelligent canvas.</div>}</div>
      <div className="grid min-h-[680px] place-items-center overflow-auto rounded-[1.5rem] bg-[#c9c5bd] p-6"><div className="w-full max-w-[760px] overflow-hidden rounded-[2rem] bg-white shadow-2xl" style={{background:theme.bg,color:theme.text}}><div className="p-7 sm:p-10"><button onClick={()=>setSelected("hero")} className={cn("w-full rounded-xl p-1 text-left",selected==="hero"&&"ring-2 ring-black/20")}><div className="mb-8 flex items-end justify-between gap-5 border-b pb-7" style={{borderColor:`${theme.text}18`}}><div><div className="text-[10px] font-bold uppercase tracking-[.25em] opacity-45">{restaurant.data?.name??"Your Restaurant"}</div><h2 className="mt-2 text-4xl font-black tracking-[-.04em]" style={{color:theme.primary}}>Menu</h2><p className="mt-2 text-sm opacity-50">{theme.tagline||"Made with intention."}</p></div><div className="hidden text-right text-[10px] font-bold uppercase tracking-[.18em] opacity-35 sm:block">Creative<br/>Edition</div></div></button><div className="grid gap-4 sm:grid-cols-2">{Array.from({length:6}).map((_,i)=><button key={i} onClick={()=>setSelected("item-card")} className={cn("overflow-hidden text-left",selected==="item-card"&&"ring-2 ring-black/25")} style={{background:theme.surface,borderRadius:Math.max(8,theme.radius)}}>{theme.showImages&&<div className="aspect-[4/3]" style={{background:`linear-gradient(135deg, ${theme.primary}22, ${theme.accent}22)`}}><div className="grid h-full place-items-center"><Camera className="size-8 opacity-20"/></div></div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">Signature Dish {i+1}</h3><p className="mt-1 text-xs opacity-50">Fresh ingredients, thoughtful preparation.</p></div><span className="shrink-0 font-bold" style={{color:theme.primary}}>{(8.5+i).toFixed(2)}</span></div></div></button>)}</div></div></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-3">{[{icon:BrainCircuit,title:"Creative Director",text:"Makes the design decision."},{icon:Layers3,title:"Editable system",text:"Every meaningful element stays changeable."},{icon:Camera,title:"Humanized imagery",text:"Photography direction feels art-directed, not generic."}].map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl bg-white/75 p-4"><Icon className="size-4"/><div className="mt-3 text-sm font-bold">{title}</div><div className="mt-1 text-xs text-black/45">{text}</div><div className="mt-3 flex items-center gap-1 text-[10px] font-bold text-black/45"><Check className="size-3"/>One unified workflow</div></div>)}</div>
    </main></div></div></div>;
}
