/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedManageRouteRouteImport } from './routes/_authenticated/manage/route'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as OTokenRouteImport } from './routes/o/$token'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as AuthenticatedManageIndexRouteImport } from './routes/_authenticated/manage/index'
import { Route as AuthenticatedManageRestaurantIdRouteRouteImport } from './routes/_authenticated/manage/$restaurantId/route'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedSuperAdminAnalyticsRouteImport } from './routes/_authenticated/super-admin/analytics'
import { Route as AuthenticatedSuperAdminAuditLogsRouteImport } from './routes/_authenticated/super-admin/audit-logs'
import { Route as AuthenticatedSuperAdminOrdersRouteImport } from './routes/_authenticated/super-admin/orders'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin/settings'
import { Route as AuthenticatedSuperAdminSubscriptionsRouteImport } from './routes/_authenticated/super-admin/subscriptions'
import { Route as AuthenticatedManageRestaurantIdIndexRouteImport } from './routes/_authenticated/manage/$restaurantId/index'
import { Route as AuthenticatedManageRestaurantIdAnalyticsRouteImport } from './routes/_authenticated/manage/$restaurantId/analytics'
import { Route as AuthenticatedManageRestaurantIdOrdersRouteImport } from './routes/_authenticated/manage/$restaurantId/orders'
import { Route as AuthenticatedManageRestaurantIdStaffRouteImport } from './routes/_authenticated/manage/$restaurantId/staff'
import { Route as AuthenticatedManageRestaurantIdTablesRouteImport } from './routes/_authenticated/manage/$restaurantId/tables'
import { Route as AuthenticatedSuperAdminRestaurantsIndexRouteImport } from './routes/_authenticated/super-admin/restaurants/index'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/route'
import { Route as AuthenticatedSuperAdminRestaurantsNewRouteImport } from './routes/_authenticated/super-admin/restaurants/new'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/index'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/analytics'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdEditRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/edit'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/menu'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/orders'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/staff'
import { Route as AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRouteImport } from './routes/_authenticated/super-admin/restaurants/$restaurantId/tables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageRouteRoute =
  AuthenticatedManageRouteRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OTokenRoute = OTokenRouteImport.update({
  id: '/o/$token',
  path: '/o/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManageIndexRoute =
  AuthenticatedManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManageRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdRouteRoute =
  AuthenticatedManageRestaurantIdRouteRouteImport.update({
    id: '/$restaurantId',
    path: '/$restaurantId',
    getParentRoute: () => AuthenticatedManageRouteRoute,
  } as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAnalyticsRoute =
  AuthenticatedSuperAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAuditLogsRoute =
  AuthenticatedSuperAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminOrdersRoute =
  AuthenticatedSuperAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminSubscriptionsRoute =
  AuthenticatedSuperAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdIndexRoute =
  AuthenticatedManageRestaurantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManageRestaurantIdRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdAnalyticsRoute =
  AuthenticatedManageRestaurantIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedManageRestaurantIdRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdOrdersRoute =
  AuthenticatedManageRestaurantIdOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedManageRestaurantIdRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdStaffRoute =
  AuthenticatedManageRestaurantIdStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedManageRestaurantIdRouteRoute,
  } as any)
const AuthenticatedManageRestaurantIdTablesRoute =
  AuthenticatedManageRestaurantIdTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AuthenticatedManageRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsIndexRoute =
  AuthenticatedSuperAdminRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsNewRoute =
  AuthenticatedSuperAdminRestaurantsNewRouteImport.update({
    id: '/restaurants/new',
    path: '/restaurants/new',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute =
  AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () =>
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manage': typeof AuthenticatedManageRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/o/$token': typeof OTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/manage/$restaurantId': typeof AuthenticatedManageRestaurantIdRouteRouteWithChildren
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/super-admin/orders': typeof AuthenticatedSuperAdminOrdersRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof AuthenticatedSuperAdminSubscriptionsRoute
  '/manage/': typeof AuthenticatedManageIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/super-admin/restaurants/$restaurantId': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteWithChildren
  '/manage/$restaurantId/analytics': typeof AuthenticatedManageRestaurantIdAnalyticsRoute
  '/manage/$restaurantId/orders': typeof AuthenticatedManageRestaurantIdOrdersRoute
  '/manage/$restaurantId/staff': typeof AuthenticatedManageRestaurantIdStaffRoute
  '/manage/$restaurantId/tables': typeof AuthenticatedManageRestaurantIdTablesRoute
  '/super-admin/restaurants/new': typeof AuthenticatedSuperAdminRestaurantsNewRoute
  '/manage/$restaurantId/': typeof AuthenticatedManageRestaurantIdIndexRoute
  '/super-admin/restaurants/': typeof AuthenticatedSuperAdminRestaurantsIndexRoute
  '/super-admin/restaurants/$restaurantId/analytics': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute
  '/super-admin/restaurants/$restaurantId/edit': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute
  '/super-admin/restaurants/$restaurantId/menu': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute
  '/super-admin/restaurants/$restaurantId/orders': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute
  '/super-admin/restaurants/$restaurantId/staff': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute
  '/super-admin/restaurants/$restaurantId/tables': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute
  '/super-admin/restaurants/$restaurantId/': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/o/$token': typeof OTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/super-admin/orders': typeof AuthenticatedSuperAdminOrdersRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof AuthenticatedSuperAdminSubscriptionsRoute
  '/manage': typeof AuthenticatedManageIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/manage/$restaurantId/analytics': typeof AuthenticatedManageRestaurantIdAnalyticsRoute
  '/manage/$restaurantId/orders': typeof AuthenticatedManageRestaurantIdOrdersRoute
  '/manage/$restaurantId/staff': typeof AuthenticatedManageRestaurantIdStaffRoute
  '/manage/$restaurantId/tables': typeof AuthenticatedManageRestaurantIdTablesRoute
  '/super-admin/restaurants/new': typeof AuthenticatedSuperAdminRestaurantsNewRoute
  '/manage/$restaurantId': typeof AuthenticatedManageRestaurantIdIndexRoute
  '/super-admin/restaurants': typeof AuthenticatedSuperAdminRestaurantsIndexRoute
  '/super-admin/restaurants/$restaurantId/analytics': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute
  '/super-admin/restaurants/$restaurantId/edit': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute
  '/super-admin/restaurants/$restaurantId/menu': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute
  '/super-admin/restaurants/$restaurantId/orders': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute
  '/super-admin/restaurants/$restaurantId/staff': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute
  '/super-admin/restaurants/$restaurantId/tables': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute
  '/super-admin/restaurants/$restaurantId': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/manage': typeof AuthenticatedManageRouteRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/o/$token': typeof OTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/manage/$restaurantId': typeof AuthenticatedManageRestaurantIdRouteRouteWithChildren
  '/_authenticated/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/_authenticated/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/_authenticated/super-admin/orders': typeof AuthenticatedSuperAdminOrdersRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/subscriptions': typeof AuthenticatedSuperAdminSubscriptionsRoute
  '/_authenticated/manage/': typeof AuthenticatedManageIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/super-admin/restaurants/$restaurantId': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteWithChildren
  '/_authenticated/manage/$restaurantId/analytics': typeof AuthenticatedManageRestaurantIdAnalyticsRoute
  '/_authenticated/manage/$restaurantId/orders': typeof AuthenticatedManageRestaurantIdOrdersRoute
  '/_authenticated/manage/$restaurantId/staff': typeof AuthenticatedManageRestaurantIdStaffRoute
  '/_authenticated/manage/$restaurantId/tables': typeof AuthenticatedManageRestaurantIdTablesRoute
  '/_authenticated/super-admin/restaurants/new': typeof AuthenticatedSuperAdminRestaurantsNewRoute
  '/_authenticated/manage/$restaurantId/': typeof AuthenticatedManageRestaurantIdIndexRoute
  '/_authenticated/super-admin/restaurants/': typeof AuthenticatedSuperAdminRestaurantsIndexRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/analytics': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/edit': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/menu': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/orders': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/staff': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/tables': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute
  '/_authenticated/super-admin/restaurants/$restaurantId/': typeof AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manage'
    | '/super-admin'
    | '/dashboard'
    | '/kitchen'
    | '/o/$token'
    | '/r/$slug'
    | '/manage/$restaurantId'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/orders'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/manage/'
    | '/super-admin/'
    | '/super-admin/restaurants/$restaurantId'
    | '/manage/$restaurantId/analytics'
    | '/manage/$restaurantId/orders'
    | '/manage/$restaurantId/staff'
    | '/manage/$restaurantId/tables'
    | '/super-admin/restaurants/new'
    | '/manage/$restaurantId/'
    | '/super-admin/restaurants/'
    | '/super-admin/restaurants/$restaurantId/analytics'
    | '/super-admin/restaurants/$restaurantId/edit'
    | '/super-admin/restaurants/$restaurantId/menu'
    | '/super-admin/restaurants/$restaurantId/orders'
    | '/super-admin/restaurants/$restaurantId/staff'
    | '/super-admin/restaurants/$restaurantId/tables'
    | '/super-admin/restaurants/$restaurantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/kitchen'
    | '/o/$token'
    | '/r/$slug'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/orders'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/manage'
    | '/super-admin'
    | '/manage/$restaurantId/analytics'
    | '/manage/$restaurantId/orders'
    | '/manage/$restaurantId/staff'
    | '/manage/$restaurantId/tables'
    | '/super-admin/restaurants/new'
    | '/manage/$restaurantId'
    | '/super-admin/restaurants'
    | '/super-admin/restaurants/$restaurantId/analytics'
    | '/super-admin/restaurants/$restaurantId/edit'
    | '/super-admin/restaurants/$restaurantId/menu'
    | '/super-admin/restaurants/$restaurantId/orders'
    | '/super-admin/restaurants/$restaurantId/staff'
    | '/super-admin/restaurants/$restaurantId/tables'
    | '/super-admin/restaurants/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/manage'
    | '/_authenticated/super-admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/kitchen'
    | '/o/$token'
    | '/r/$slug'
    | '/_authenticated/manage/$restaurantId'
    | '/_authenticated/super-admin/analytics'
    | '/_authenticated/super-admin/audit-logs'
    | '/_authenticated/super-admin/orders'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/subscriptions'
    | '/_authenticated/manage/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/super-admin/restaurants/$restaurantId'
    | '/_authenticated/manage/$restaurantId/analytics'
    | '/_authenticated/manage/$restaurantId/orders'
    | '/_authenticated/manage/$restaurantId/staff'
    | '/_authenticated/manage/$restaurantId/tables'
    | '/_authenticated/super-admin/restaurants/new'
    | '/_authenticated/manage/$restaurantId/'
    | '/_authenticated/super-admin/restaurants/'
    | '/_authenticated/super-admin/restaurants/$restaurantId/analytics'
    | '/_authenticated/super-admin/restaurants/$restaurantId/edit'
    | '/_authenticated/super-admin/restaurants/$restaurantId/menu'
    | '/_authenticated/super-admin/restaurants/$restaurantId/orders'
    | '/_authenticated/super-admin/restaurants/$restaurantId/staff'
    | '/_authenticated/super-admin/restaurants/$restaurantId/tables'
    | '/_authenticated/super-admin/restaurants/$restaurantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OTokenRoute: typeof OTokenRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage': {
      id: '/_authenticated/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AuthenticatedManageRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/o/$token': {
      id: '/o/$token'
      path: '/o/$token'
      fullPath: '/o/$token'
      preLoaderRoute: typeof OTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manage/': {
      id: '/_authenticated/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof AuthenticatedManageIndexRouteImport
      parentRoute: typeof AuthenticatedManageRouteRoute
    }
    '/_authenticated/manage/$restaurantId': {
      id: '/_authenticated/manage/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/manage/$restaurantId'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdRouteRouteImport
      parentRoute: typeof AuthenticatedManageRouteRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/analytics': {
      id: '/_authenticated/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/audit-logs': {
      id: '/_authenticated/super-admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/orders': {
      id: '/_authenticated/super-admin/orders'
      path: '/orders'
      fullPath: '/super-admin/orders'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/subscriptions': {
      id: '/_authenticated/super-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedSuperAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/manage/$restaurantId/': {
      id: '/_authenticated/manage/$restaurantId/'
      path: '/'
      fullPath: '/manage/$restaurantId/'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdIndexRouteImport
      parentRoute: typeof AuthenticatedManageRestaurantIdRouteRoute
    }
    '/_authenticated/manage/$restaurantId/analytics': {
      id: '/_authenticated/manage/$restaurantId/analytics'
      path: '/analytics'
      fullPath: '/manage/$restaurantId/analytics'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedManageRestaurantIdRouteRoute
    }
    '/_authenticated/manage/$restaurantId/orders': {
      id: '/_authenticated/manage/$restaurantId/orders'
      path: '/orders'
      fullPath: '/manage/$restaurantId/orders'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdOrdersRouteImport
      parentRoute: typeof AuthenticatedManageRestaurantIdRouteRoute
    }
    '/_authenticated/manage/$restaurantId/staff': {
      id: '/_authenticated/manage/$restaurantId/staff'
      path: '/staff'
      fullPath: '/manage/$restaurantId/staff'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdStaffRouteImport
      parentRoute: typeof AuthenticatedManageRestaurantIdRouteRoute
    }
    '/_authenticated/manage/$restaurantId/tables': {
      id: '/_authenticated/manage/$restaurantId/tables'
      path: '/tables'
      fullPath: '/manage/$restaurantId/tables'
      preLoaderRoute: typeof AuthenticatedManageRestaurantIdTablesRouteImport
      parentRoute: typeof AuthenticatedManageRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/': {
      id: '/_authenticated/super-admin/restaurants/'
      path: '/restaurants'
      fullPath: '/super-admin/restaurants/'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/super-admin/restaurants/$restaurantId'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/restaurants/new': {
      id: '/_authenticated/super-admin/restaurants/new'
      path: '/restaurants/new'
      fullPath: '/super-admin/restaurants/new'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsNewRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/'
      path: '/'
      fullPath: '/super-admin/restaurants/$restaurantId/'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/analytics': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/analytics'
      path: '/analytics'
      fullPath: '/super-admin/restaurants/$restaurantId/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/edit': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/edit'
      path: '/edit'
      fullPath: '/super-admin/restaurants/$restaurantId/edit'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdEditRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/menu': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/menu'
      path: '/menu'
      fullPath: '/super-admin/restaurants/$restaurantId/menu'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/orders': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/orders'
      path: '/orders'
      fullPath: '/super-admin/restaurants/$restaurantId/orders'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/staff': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/staff'
      path: '/staff'
      fullPath: '/super-admin/restaurants/$restaurantId/staff'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
    '/_authenticated/super-admin/restaurants/$restaurantId/tables': {
      id: '/_authenticated/super-admin/restaurants/$restaurantId/tables'
      path: '/tables'
      fullPath: '/super-admin/restaurants/$restaurantId/tables'
      preLoaderRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute
    }
  }
}

interface AuthenticatedManageRestaurantIdRouteRouteChildren {
  AuthenticatedManageRestaurantIdAnalyticsRoute: typeof AuthenticatedManageRestaurantIdAnalyticsRoute
  AuthenticatedManageRestaurantIdOrdersRoute: typeof AuthenticatedManageRestaurantIdOrdersRoute
  AuthenticatedManageRestaurantIdStaffRoute: typeof AuthenticatedManageRestaurantIdStaffRoute
  AuthenticatedManageRestaurantIdTablesRoute: typeof AuthenticatedManageRestaurantIdTablesRoute
  AuthenticatedManageRestaurantIdIndexRoute: typeof AuthenticatedManageRestaurantIdIndexRoute
}

const AuthenticatedManageRestaurantIdRouteRouteChildren: AuthenticatedManageRestaurantIdRouteRouteChildren =
  {
    AuthenticatedManageRestaurantIdAnalyticsRoute:
      AuthenticatedManageRestaurantIdAnalyticsRoute,
    AuthenticatedManageRestaurantIdOrdersRoute:
      AuthenticatedManageRestaurantIdOrdersRoute,
    AuthenticatedManageRestaurantIdStaffRoute:
      AuthenticatedManageRestaurantIdStaffRoute,
    AuthenticatedManageRestaurantIdTablesRoute:
      AuthenticatedManageRestaurantIdTablesRoute,
    AuthenticatedManageRestaurantIdIndexRoute:
      AuthenticatedManageRestaurantIdIndexRoute,
  }

const AuthenticatedManageRestaurantIdRouteRouteWithChildren =
  AuthenticatedManageRestaurantIdRouteRoute._addFileChildren(
    AuthenticatedManageRestaurantIdRouteRouteChildren,
  )

interface AuthenticatedManageRouteRouteChildren {
  AuthenticatedManageRestaurantIdRouteRoute: typeof AuthenticatedManageRestaurantIdRouteRouteWithChildren
  AuthenticatedManageIndexRoute: typeof AuthenticatedManageIndexRoute
}

const AuthenticatedManageRouteRouteChildren: AuthenticatedManageRouteRouteChildren =
  {
    AuthenticatedManageRestaurantIdRouteRoute:
      AuthenticatedManageRestaurantIdRouteRouteWithChildren,
    AuthenticatedManageIndexRoute: AuthenticatedManageIndexRoute,
  }

const AuthenticatedManageRouteRouteWithChildren =
  AuthenticatedManageRouteRoute._addFileChildren(
    AuthenticatedManageRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteChildren {
  AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute
}

const AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteChildren: AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteChildren =
  {
    AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdAnalyticsRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdEditRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdMenuRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdOrdersRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdStaffRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdTablesRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdIndexRoute,
  }

const AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteWithChildren =
  AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminAnalyticsRoute: typeof AuthenticatedSuperAdminAnalyticsRoute
  AuthenticatedSuperAdminAuditLogsRoute: typeof AuthenticatedSuperAdminAuditLogsRoute
  AuthenticatedSuperAdminOrdersRoute: typeof AuthenticatedSuperAdminOrdersRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminSubscriptionsRoute: typeof AuthenticatedSuperAdminSubscriptionsRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute: typeof AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteWithChildren
  AuthenticatedSuperAdminRestaurantsNewRoute: typeof AuthenticatedSuperAdminRestaurantsNewRoute
  AuthenticatedSuperAdminRestaurantsIndexRoute: typeof AuthenticatedSuperAdminRestaurantsIndexRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminAnalyticsRoute:
      AuthenticatedSuperAdminAnalyticsRoute,
    AuthenticatedSuperAdminAuditLogsRoute:
      AuthenticatedSuperAdminAuditLogsRoute,
    AuthenticatedSuperAdminOrdersRoute: AuthenticatedSuperAdminOrdersRoute,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminSubscriptionsRoute:
      AuthenticatedSuperAdminSubscriptionsRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRoute:
      AuthenticatedSuperAdminRestaurantsRestaurantIdRouteRouteWithChildren,
    AuthenticatedSuperAdminRestaurantsNewRoute:
      AuthenticatedSuperAdminRestaurantsNewRoute,
    AuthenticatedSuperAdminRestaurantsIndexRoute:
      AuthenticatedSuperAdminRestaurantsIndexRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedManageRouteRoute: typeof AuthenticatedManageRouteRouteWithChildren
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedManageRouteRoute: AuthenticatedManageRouteRouteWithChildren,
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OTokenRoute: OTokenRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
