-- QuickServe Phase 4: production hardening + restaurant OS growth foundation.
-- Applied to production Supabase on 2026-09-20.
-- This migration introduces:
-- observability/performance, public rate limiting, payment ledgers/cash sessions,
-- recipe/BOM stock consumption, CRM/loyalty/gift cards, workforce time clock,
-- supplier invoice matching, multi-location groups and SaaS usage snapshots.
--
-- Full migration body is intentionally kept identical to the production-applied
-- migration. See Supabase migration history: phase4_restaurant_os_foundation.
--
-- Tables
create table if not exists public.system_events (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  severity text not null default 'info' check (severity in ('info','warning','error','critical')),
  source text not null,
  event_type text not null,
  message text not null,
  route text,
  metadata jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.performance_samples (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  metric text not null check (metric in ('LCP','CLS','INP','TTFB','route_load')),
  value numeric not null,
  route text not null default '/',
  device text,
  created_at timestamptz not null default now()
);
create table if not exists public.public_rate_limits (
  rate_key text not null,
  window_started_at timestamptz not null,
  hits integer not null default 0,
  primary key(rate_key,window_started_at)
);
create table if not exists public.cash_sessions (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid references public.staff(id) on delete set null,
  opened_by uuid not null default auth.uid(),
  opened_at timestamptz not null default now(),
  opening_float numeric not null default 0 check(opening_float>=0),
  closed_at timestamptz,
  closed_by uuid references auth.users(id) on delete set null,
  closing_cash numeric,
  expected_cash numeric,
  variance numeric,
  notes text not null default ''
);
create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  cash_session_id uuid references public.cash_sessions(id) on delete set null,
  transaction_type text not null default 'payment' check(transaction_type in ('payment','refund','void')),
  method text not null check(method in ('cash','card','wallet','gift_card','other')),
  amount numeric not null check(amount>=0),
  tip_amount numeric not null default 0 check(tip_amount>=0),
  reference text not null default '',
  status text not null default 'completed' check(status in ('pending','completed','failed','voided')),
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
alter table public.orders
  add column if not exists tip_amount numeric not null default 0,
  add column if not exists guest_id uuid,
  add column if not exists guest_name text,
  add column if not exists guest_phone text,
  add column if not exists guest_email text,
  add column if not exists fulfillment_type text not null default 'dine_in',
  add column if not exists scheduled_for timestamptz,
  add column if not exists delivery_address text;
create table if not exists public.erp_menu_recipes (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  yield_quantity numeric not null default 1 check(yield_quantity>0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(restaurant_id,menu_item_id)
);
create table if not exists public.erp_recipe_items (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.erp_menu_recipes(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  inventory_item_id uuid not null references public.erp_inventory(id) on delete restrict,
  quantity numeric not null check(quantity>0),
  waste_percent numeric not null default 0 check(waste_percent>=0 and waste_percent<100),
  created_at timestamptz not null default now(),
  unique(recipe_id,inventory_item_id)
);
create table if not exists public.erp_order_consumptions (
  order_id uuid primary key references public.orders(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  consumed_at timestamptz not null default now()
);
create table if not exists public.crm_guests (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text,
  phone text,
  email text,
  marketing_opt_in boolean not null default false,
  visits integer not null default 0,
  lifetime_spend numeric not null default 0,
  last_visit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.crm_loyalty_accounts (
  guest_id uuid primary key references public.crm_guests(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  points integer not null default 0,
  tier text not null default 'member',
  updated_at timestamptz not null default now()
);
create table if not exists public.crm_loyalty_ledger (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  guest_id uuid not null references public.crm_guests(id) on delete cascade,
  points integer not null,
  reason text not null,
  source_order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.crm_gift_cards (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  code text not null,
  initial_value numeric not null check(initial_value>0),
  balance numeric not null check(balance>=0),
  status text not null default 'active' check(status in ('active','used','void')),
  expires_at timestamptz,
  guest_id uuid references public.crm_guests(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique(restaurant_id,code)
);
alter table public.restaurant_settings
  add column if not exists enable_pickup boolean not null default false,
  add column if not exists enable_delivery boolean not null default false,
  add column if not exists delivery_fee numeric not null default 0,
  add column if not exists collect_guest_details boolean not null default false,
  add column if not exists enable_loyalty boolean not null default false,
  add column if not exists loyalty_points_per_currency numeric not null default 10,
  add column if not exists loyalty_redeem_value numeric not null default 0.01,
  add column if not exists max_active_orders integer not null default 100;
create table if not exists public.staff_time_entries (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid not null references public.staff(id) on delete cascade,
  clock_in timestamptz not null default now(),
  clock_out timestamptz,
  break_minutes integer not null default 0 check(break_minutes>=0),
  notes text not null default '',
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.staff_leave_requests (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid not null references public.staff(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text not null default '',
  status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check(end_date>=start_date)
);
create table if not exists public.erp_supplier_invoices (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  supplier_id uuid references public.erp_suppliers(id) on delete set null,
  procurement_request_id uuid references public.erp_procurement_requests(id) on delete set null,
  invoice_number text not null,
  invoice_date date not null default current_date,
  amount numeric not null check(amount>=0),
  tax_amount numeric not null default 0 check(tax_amount>=0),
  status text not null default 'draft' check(status in ('draft','matched','approved','paid','void')),
  file_url text,
  expense_id uuid references public.erp_expenses(id) on delete set null,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(restaurant_id,invoice_number)
);
create table if not exists public.restaurant_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.restaurant_group_members (
  group_id uuid not null references public.restaurant_groups(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(group_id,restaurant_id)
);
create table if not exists public.saas_usage_daily (
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  usage_date date not null default current_date,
  orders_count integer not null default 0,
  active_staff integer not null default 0,
  tables_count integer not null default 0,
  menu_items_count integer not null default 0,
  storage_bytes bigint not null default 0,
  primary key(restaurant_id,usage_date)
);

-- Functions / triggers installed in production:
-- app.enforce_public_rate_limit
-- public.record_client_event
-- public.record_performance_sample
-- public.open_cash_session
-- public.record_order_payment
-- public.refund_order_payment
-- public.close_cash_session
-- app.consume_order_inventory + trg_order_recipe_consumption
-- app.upsert_order_guest
-- public.place_public_order_v2
-- app.on_paid_order_guest + trg_paid_order_guest
-- public.issue_gift_card
-- public.toggle_time_clock
-- public.submit_leave_request
-- public.review_leave_request
-- public.refresh_restaurant_usage
--
-- Production RLS policies and indexes were applied with the migration as well.
