
-- QuickServe Phase 4: production hardening + restaurant OS growth foundation
-- 2026-09-20

-- ---------------------------------------------------------------------------
-- 1) Observability, performance and public abuse controls
-- ---------------------------------------------------------------------------
create table if not exists public.system_events (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  severity text not null default 'info' check (severity in ('info','warning','error','critical')),
  source text not null,
  event_type text not null,
  message text not null,
  route text,
  metadata jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists system_events_restaurant_created_idx on public.system_events(restaurant_id,created_at desc);
create index if not exists system_events_severity_created_idx on public.system_events(severity,created_at desc);
alter table public.system_events enable row level security;
drop policy if exists system_events_select on public.system_events;
create policy system_events_select on public.system_events for select to authenticated using (
  app.is_super_admin()
  or (restaurant_id is not null and (
    app.has_capability(restaurant_id,'manage_restaurant')
    or app.has_capability(restaurant_id,'view_analytics')
  ))
);
grant select on public.system_events to authenticated;
revoke insert,update,delete on public.system_events from authenticated;

create table if not exists public.performance_samples (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  metric text not null check (metric in ('LCP','CLS','INP','TTFB','route_load')),
  value numeric not null,
  route text not null default '/',
  device text,
  created_at timestamptz not null default now()
);
create index if not exists performance_samples_metric_created_idx on public.performance_samples(metric,created_at desc);
create index if not exists performance_samples_restaurant_created_idx on public.performance_samples(restaurant_id,created_at desc);
alter table public.performance_samples enable row level security;
drop policy if exists performance_samples_select on public.performance_samples;
create policy performance_samples_select on public.performance_samples for select to authenticated using (
  app.is_super_admin()
  or (restaurant_id is not null and app.has_capability(restaurant_id,'view_analytics'))
);
grant select on public.performance_samples to authenticated;
revoke insert,update,delete on public.performance_samples from authenticated;

create table if not exists public.public_rate_limits (
  rate_key text not null,
  window_started_at timestamptz not null,
  hits integer not null default 0,
  primary key(rate_key,window_started_at)
);

create or replace function app.enforce_public_rate_limit(_key text,_max_hits integer,_window_seconds integer)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  _window timestamptz;
  _hits integer;
begin
  if _max_hits <= 0 or _window_seconds <= 0 then return; end if;
  _window := to_timestamp(floor(extract(epoch from now())/_window_seconds)*_window_seconds);
  insert into public.public_rate_limits(rate_key,window_started_at,hits)
  values(left(_key,240),_window,1)
  on conflict(rate_key,window_started_at)
  do update set hits=public.public_rate_limits.hits+1
  returning hits into _hits;
  if _hits > _max_hits then
    raise exception 'Too many requests. Please try again shortly.' using errcode='P0001';
  end if;
end;
$$;
revoke all on function app.enforce_public_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function app.enforce_public_rate_limit(text,integer,integer) to service_role;

create or replace function public.record_client_event(
  _severity text,
  _event_type text,
  _message text,
  _route text default null,
  _metadata jsonb default '{}'::jsonb,
  _restaurant_id uuid default null
) returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if (select auth.uid()) is null then return; end if;
  if _restaurant_id is not null and not app.has_restaurant_access(_restaurant_id) and not app.is_super_admin() then
    _restaurant_id := null;
  end if;
  insert into public.system_events(restaurant_id,severity,source,event_type,message,route,metadata,user_id)
  values(
    _restaurant_id,
    case when _severity in ('info','warning','error','critical') then _severity else 'error' end,
    'web',
    left(coalesce(_event_type,'client_error'),120),
    left(coalesce(_message,'Unknown client error'),2000),
    left(_route,500),
    coalesce(_metadata,'{}'::jsonb),
    (select auth.uid())
  );
end;
$$;
revoke all on function public.record_client_event(text,text,text,text,jsonb,uuid) from public,anon;
grant execute on function public.record_client_event(text,text,text,text,jsonb,uuid) to authenticated;

create or replace function public.record_performance_sample(
  _metric text,_value numeric,_route text,_device text default null,_restaurant_id uuid default null
) returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if (select auth.uid()) is null then return; end if;
  if _metric not in ('LCP','CLS','INP','TTFB','route_load') then return; end if;
  if _value < 0 or _value > 600000 then return; end if;
  if _restaurant_id is not null and not app.has_restaurant_access(_restaurant_id) and not app.is_super_admin() then
    _restaurant_id := null;
  end if;
  insert into public.performance_samples(restaurant_id,metric,value,route,device)
  values(_restaurant_id,_metric,_value,left(coalesce(_route,'/'),500),left(_device,80));
end;
$$;
revoke all on function public.record_performance_sample(text,numeric,text,text,uuid) from public,anon;
grant execute on function public.record_performance_sample(text,numeric,text,text,uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 2) Payments / cashier reconciliation
-- ---------------------------------------------------------------------------
create table if not exists public.cash_sessions (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid references public.staff(id) on delete set null,
  opened_by uuid not null default auth.uid(),
  opened_at timestamptz not null default now(),
  opening_float numeric not null default 0 check(opening_float>=0),
  closed_at timestamptz,
  closed_by uuid references auth.users(id) on delete set null,
  closing_cash numeric,
  expected_cash numeric,
  variance numeric,
  notes text not null default ''
);
create index if not exists cash_sessions_restaurant_opened_idx on public.cash_sessions(restaurant_id,opened_at desc);
alter table public.cash_sessions enable row level security;
drop policy if exists cash_sessions_select on public.cash_sessions;
create policy cash_sessions_select on public.cash_sessions for select to authenticated using (
  app.has_capability(restaurant_id,'manage_payments')
  or app.has_capability(restaurant_id,'manage_restaurant')
);
grant select on public.cash_sessions to authenticated;
revoke insert,update,delete on public.cash_sessions from authenticated;

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  cash_session_id uuid references public.cash_sessions(id) on delete set null,
  transaction_type text not null default 'payment' check(transaction_type in ('payment','refund','void')),
  method text not null check(method in ('cash','card','wallet','gift_card','other')),
  amount numeric not null check(amount>=0),
  tip_amount numeric not null default 0 check(tip_amount>=0),
  reference text not null default '',
  status text not null default 'completed' check(status in ('pending','completed','failed','voided')),
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists payment_transactions_restaurant_created_idx on public.payment_transactions(restaurant_id,created_at desc);
create index if not exists payment_transactions_order_idx on public.payment_transactions(order_id,created_at);
create index if not exists payment_transactions_cash_session_idx on public.payment_transactions(cash_session_id) where cash_session_id is not null;
alter table public.payment_transactions enable row level security;
drop policy if exists payment_transactions_select on public.payment_transactions;
create policy payment_transactions_select on public.payment_transactions for select to authenticated using (
  app.has_capability(restaurant_id,'manage_payments')
  or app.has_capability(restaurant_id,'manage_finance')
  or app.has_capability(restaurant_id,'manage_restaurant')
);
grant select on public.payment_transactions to authenticated;
revoke insert,update,delete on public.payment_transactions from authenticated;

alter table public.orders
  add column if not exists tip_amount numeric not null default 0,
  add column if not exists guest_id uuid,
  add column if not exists guest_name text,
  add column if not exists guest_phone text,
  add column if not exists guest_email text,
  add column if not exists fulfillment_type text not null default 'dine_in',
  add column if not exists scheduled_for timestamptz,
  add column if not exists delivery_address text;

do $$
begin
  if not exists(select 1 from pg_constraint where conname='orders_fulfillment_type_check') then
    alter table public.orders add constraint orders_fulfillment_type_check
      check(fulfillment_type in ('dine_in','pickup','delivery'));
  end if;
end $$;

create or replace function public.open_cash_session(_opening_float numeric default 0,_staff_id uuid default null)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare _restaurant_id uuid; _id uuid;
begin
  select restaurant_id into _restaurant_id
  from public.staff
  where auth_user_id=(select auth.uid()) and is_active
  order by updated_at desc limit 1;
  if _restaurant_id is null or not (
    app.has_capability(_restaurant_id,'manage_payments')
    or app.has_capability(_restaurant_id,'manage_restaurant')
  ) then raise exception 'Cashier access is required'; end if;
  if exists(select 1 from public.cash_sessions where restaurant_id=_restaurant_id and opened_by=(select auth.uid()) and closed_at is null) then
    select id into _id from public.cash_sessions where restaurant_id=_restaurant_id and opened_by=(select auth.uid()) and closed_at is null order by opened_at desc limit 1;
    return _id;
  end if;
  insert into public.cash_sessions(restaurant_id,staff_id,opening_float)
  values(_restaurant_id,_staff_id,greatest(coalesce(_opening_float,0),0))
  returning id into _id;
  return _id;
end;
$$;
revoke all on function public.open_cash_session(numeric,uuid) from public,anon;
grant execute on function public.open_cash_session(numeric,uuid) to authenticated,service_role;

create or replace function public.record_order_payment(
  _order_id uuid,_method text,_amount numeric,_tip numeric default 0,_reference text default '',_cash_session_id uuid default null
) returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare
  _order public.orders%rowtype;
  _id uuid;
  _paid numeric;
begin
  select * into _order from public.orders where id=_order_id for update;
  if _order.id is null then raise exception 'Order not found'; end if;
  if not (
    app.has_capability(_order.restaurant_id,'manage_payments')
    or app.has_capability(_order.restaurant_id,'manage_restaurant')
    or app.is_super_admin()
  ) then raise exception 'Payment access is required'; end if;
  if _method not in ('cash','card','wallet','gift_card','other') then raise exception 'Unsupported payment method'; end if;
  if coalesce(_amount,0)<=0 then raise exception 'Payment amount must be positive'; end if;

  insert into public.payment_transactions(
    restaurant_id,order_id,cash_session_id,transaction_type,method,amount,tip_amount,reference,status
  ) values(
    _order.restaurant_id,_order_id,_cash_session_id,'payment',_method,_amount,greatest(coalesce(_tip,0),0),left(coalesce(_reference,''),200),'completed'
  ) returning id into _id;

  select coalesce(sum(case when transaction_type='payment' and status='completed' then amount else 0 end),0)
       - coalesce(sum(case when transaction_type='refund' and status='completed' then amount else 0 end),0)
  into _paid
  from public.payment_transactions where order_id=_order_id;

  update public.orders
  set tip_amount=tip_amount+greatest(coalesce(_tip,0),0),
      payment_status=case when _paid>=total then 'paid'::public.payment_status else payment_status end,
      status=case when _paid>=total and status='served' then 'paid'::public.order_status else status end,
      updated_at=now()
  where id=_order_id;

  return _id;
end;
$$;
revoke all on function public.record_order_payment(uuid,text,numeric,numeric,text,uuid) from public,anon;
grant execute on function public.record_order_payment(uuid,text,numeric,numeric,text,uuid) to authenticated,service_role;

create or replace function public.refund_order_payment(
  _order_id uuid,_amount numeric,_method text default 'card',_reference text default ''
) returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare _order public.orders%rowtype; _id uuid; _net numeric;
begin
  select * into _order from public.orders where id=_order_id for update;
  if _order.id is null then raise exception 'Order not found'; end if;
  if not (
    app.has_capability(_order.restaurant_id,'manage_payments')
    or app.has_capability(_order.restaurant_id,'manage_restaurant')
    or app.is_super_admin()
  ) then raise exception 'Payment access is required'; end if;
  if coalesce(_amount,0)<=0 then raise exception 'Refund amount must be positive'; end if;
  insert into public.payment_transactions(restaurant_id,order_id,transaction_type,method,amount,reference,status)
  values(_order.restaurant_id,_order_id,'refund',case when _method in ('cash','card','wallet','gift_card','other') then _method else 'other' end,_amount,left(coalesce(_reference,''),200),'completed')
  returning id into _id;
  select coalesce(sum(case when transaction_type='payment' and status='completed' then amount else 0 end),0)
       - coalesce(sum(case when transaction_type='refund' and status='completed' then amount else 0 end),0)
  into _net from public.payment_transactions where order_id=_order_id;
  if _net<=0 then update public.orders set payment_status='refunded',updated_at=now() where id=_order_id; end if;
  return _id;
end;
$$;
revoke all on function public.refund_order_payment(uuid,numeric,text,text) from public,anon;
grant execute on function public.refund_order_payment(uuid,numeric,text,text) to authenticated,service_role;

create or replace function public.close_cash_session(_session_id uuid,_closing_cash numeric,_notes text default '')
returns void
language plpgsql
security definer
set search_path=''
as $$
declare _session public.cash_sessions%rowtype; _expected numeric;
begin
  select * into _session from public.cash_sessions where id=_session_id for update;
  if _session.id is null or _session.closed_at is not null then raise exception 'Open cash session not found'; end if;
  if not (
    app.has_capability(_session.restaurant_id,'manage_payments')
    or app.has_capability(_session.restaurant_id,'manage_restaurant')
    or app.is_super_admin()
  ) then raise exception 'Payment access is required'; end if;
  select _session.opening_float
    + coalesce(sum(case when transaction_type='payment' and method='cash' and status='completed' then amount else 0 end),0)
    - coalesce(sum(case when transaction_type='refund' and method='cash' and status='completed' then amount else 0 end),0)
  into _expected
  from public.payment_transactions where cash_session_id=_session_id;
  update public.cash_sessions
  set closed_at=now(),closed_by=(select auth.uid()),closing_cash=_closing_cash,expected_cash=_expected,
      variance=coalesce(_closing_cash,0)-_expected,notes=left(coalesce(_notes,''),1000)
  where id=_session_id;
end;
$$;
revoke all on function public.close_cash_session(uuid,numeric,text) from public,anon;
grant execute on function public.close_cash_session(uuid,numeric,text) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 3) Recipe/BOM + theoretical food cost and automatic consumption
-- ---------------------------------------------------------------------------
create table if not exists public.erp_menu_recipes (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  yield_quantity numeric not null default 1 check(yield_quantity>0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(restaurant_id,menu_item_id)
);
create table if not exists public.erp_recipe_items (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.erp_menu_recipes(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  inventory_item_id uuid not null references public.erp_inventory(id) on delete restrict,
  quantity numeric not null check(quantity>0),
  waste_percent numeric not null default 0 check(waste_percent>=0 and waste_percent<100),
  created_at timestamptz not null default now(),
  unique(recipe_id,inventory_item_id)
);
create index if not exists erp_recipe_items_inventory_idx on public.erp_recipe_items(inventory_item_id);
create table if not exists public.erp_order_consumptions (
  order_id uuid primary key references public.orders(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  consumed_at timestamptz not null default now()
);
alter table public.erp_menu_recipes enable row level security;
alter table public.erp_recipe_items enable row level security;
alter table public.erp_order_consumptions enable row level security;
drop policy if exists erp_menu_recipes_all on public.erp_menu_recipes;
create policy erp_menu_recipes_all on public.erp_menu_recipes for all to authenticated
using (app.has_capability(restaurant_id,'manage_inventory') or app.has_capability(restaurant_id,'manage_restaurant'))
with check(app.has_capability(restaurant_id,'manage_inventory') or app.has_capability(restaurant_id,'manage_restaurant'));
drop policy if exists erp_recipe_items_all on public.erp_recipe_items;
create policy erp_recipe_items_all on public.erp_recipe_items for all to authenticated
using (app.has_capability(restaurant_id,'manage_inventory') or app.has_capability(restaurant_id,'manage_restaurant'))
with check(app.has_capability(restaurant_id,'manage_inventory') or app.has_capability(restaurant_id,'manage_restaurant'));
drop policy if exists erp_order_consumptions_select on public.erp_order_consumptions;
create policy erp_order_consumptions_select on public.erp_order_consumptions for select to authenticated
using(app.has_capability(restaurant_id,'manage_inventory') or app.has_capability(restaurant_id,'manage_restaurant'));
grant select,insert,update,delete on public.erp_menu_recipes,public.erp_recipe_items to authenticated;
grant select on public.erp_order_consumptions to authenticated;

create or replace function app.consume_order_inventory(_order_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  _order public.orders%rowtype;
  _line record;
  _cost numeric;
  _qty numeric;
begin
  select * into _order from public.orders where id=_order_id;
  if _order.id is null then return; end if;
  insert into public.erp_order_consumptions(order_id,restaurant_id)
  values(_order.id,_order.restaurant_id)
  on conflict(order_id) do nothing;
  if not found then return; end if;

  for _line in
    select ri.inventory_item_id,
           sum((oi.quantity::numeric * ri.quantity * (1 + ri.waste_percent/100.0)) / greatest(r.yield_quantity,0.000001)) as qty
    from public.order_items oi
    join public.erp_menu_recipes r on r.menu_item_id=oi.menu_item_id and r.restaurant_id=oi.restaurant_id
    join public.erp_recipe_items ri on ri.recipe_id=r.id and ri.restaurant_id=r.restaurant_id
    where oi.order_id=_order_id
    group by ri.inventory_item_id
  loop
    _qty:=_line.qty;
    select coalesce((
      select m.unit_cost from public.erp_stock_movements m
      where m.restaurant_id=_order.restaurant_id and m.item_id=_line.inventory_item_id and m.unit_cost>0
      order by m.created_at desc limit 1
    ),0) into _cost;
    begin
      insert into public.erp_stock_movements(
        restaurant_id,item_id,quantity,unit_cost,movement_type,reason,created_by
      ) values(
        _order.restaurant_id,_line.inventory_item_id,-_qty,_cost,'issue',
        'Recipe consumption · '||_order.order_number,
        coalesce((select auth.uid()),'00000000-0000-0000-0000-000000000000'::uuid)
      );
    exception when others then
      insert into public.system_events(restaurant_id,severity,source,event_type,message,metadata)
      values(_order.restaurant_id,'warning','inventory','recipe_consumption_failed',sqlerrm,jsonb_build_object('order_id',_order.id,'inventory_item_id',_line.inventory_item_id,'quantity',_qty));
    end;
  end loop;
end;
$$;

create or replace function app.on_order_recipe_consumption()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if new.status in ('accepted','preparing') and old.status is distinct from new.status then
    perform app.consume_order_inventory(new.id);
  end if;
  return new;
end;
$$;
drop trigger if exists trg_order_recipe_consumption on public.orders;
create trigger trg_order_recipe_consumption
after update of status on public.orders
for each row execute function app.on_order_recipe_consumption();

-- ---------------------------------------------------------------------------
-- 4) CRM, loyalty and gift cards
-- ---------------------------------------------------------------------------
create table if not exists public.crm_guests (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text,
  phone text,
  email text,
  marketing_opt_in boolean not null default false,
  visits integer not null default 0,
  lifetime_spend numeric not null default 0,
  last_visit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists crm_guests_restaurant_phone_uidx on public.crm_guests(restaurant_id,phone) where phone is not null and phone<>'';
create unique index if not exists crm_guests_restaurant_email_uidx on public.crm_guests(restaurant_id,lower(email)) where email is not null and email<>'';
create index if not exists crm_guests_last_visit_idx on public.crm_guests(restaurant_id,last_visit_at desc);

do $$
begin
  if not exists(select 1 from pg_constraint where conname='orders_guest_id_fkey') then
    alter table public.orders add constraint orders_guest_id_fkey foreign key(guest_id) references public.crm_guests(id) on delete set null;
  end if;
end $$;

create table if not exists public.crm_loyalty_accounts (
  guest_id uuid primary key references public.crm_guests(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  points integer not null default 0,
  tier text not null default 'member',
  updated_at timestamptz not null default now()
);
create table if not exists public.crm_loyalty_ledger (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  guest_id uuid not null references public.crm_guests(id) on delete cascade,
  points integer not null,
  reason text not null,
  source_order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);
create unique index if not exists crm_loyalty_paid_order_uidx on public.crm_loyalty_ledger(source_order_id) where source_order_id is not null and points>0;
create index if not exists crm_loyalty_guest_created_idx on public.crm_loyalty_ledger(guest_id,created_at desc);

create table if not exists public.crm_gift_cards (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  code text not null,
  initial_value numeric not null check(initial_value>0),
  balance numeric not null check(balance>=0),
  status text not null default 'active' check(status in ('active','used','void')),
  expires_at timestamptz,
  guest_id uuid references public.crm_guests(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique(restaurant_id,code)
);

alter table public.crm_guests enable row level security;
alter table public.crm_loyalty_accounts enable row level security;
alter table public.crm_loyalty_ledger enable row level security;
alter table public.crm_gift_cards enable row level security;
drop policy if exists crm_guests_manage on public.crm_guests;
create policy crm_guests_manage on public.crm_guests for all to authenticated using(
  app.has_capability(restaurant_id,'manage_restaurant') or app.has_capability(restaurant_id,'view_analytics')
) with check(app.has_capability(restaurant_id,'manage_restaurant'));
drop policy if exists crm_loyalty_accounts_select on public.crm_loyalty_accounts;
create policy crm_loyalty_accounts_select on public.crm_loyalty_accounts for select to authenticated using(
  app.has_capability(restaurant_id,'manage_restaurant') or app.has_capability(restaurant_id,'view_analytics')
);
drop policy if exists crm_loyalty_ledger_select on public.crm_loyalty_ledger;
create policy crm_loyalty_ledger_select on public.crm_loyalty_ledger for select to authenticated using(
  app.has_capability(restaurant_id,'manage_restaurant') or app.has_capability(restaurant_id,'view_analytics')
);
drop policy if exists crm_gift_cards_manage on public.crm_gift_cards;
create policy crm_gift_cards_manage on public.crm_gift_cards for all to authenticated using(
  app.has_capability(restaurant_id,'manage_payments') or app.has_capability(restaurant_id,'manage_restaurant')
) with check(app.has_capability(restaurant_id,'manage_payments') or app.has_capability(restaurant_id,'manage_restaurant'));
grant select,insert,update on public.crm_guests to authenticated;
grant select on public.crm_loyalty_accounts,public.crm_loyalty_ledger to authenticated;
grant select,insert,update on public.crm_gift_cards to authenticated;

alter table public.restaurant_settings
  add column if not exists enable_pickup boolean not null default false,
  add column if not exists enable_delivery boolean not null default false,
  add column if not exists delivery_fee numeric not null default 0,
  add column if not exists collect_guest_details boolean not null default false,
  add column if not exists enable_loyalty boolean not null default false,
  add column if not exists loyalty_points_per_currency numeric not null default 10,
  add column if not exists loyalty_redeem_value numeric not null default 0.01,
  add column if not exists max_active_orders integer not null default 100;

create or replace function app.upsert_order_guest(
  _restaurant_id uuid,_name text,_phone text,_email text
) returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare _id uuid;
begin
  if nullif(btrim(coalesce(_phone,'')),'') is null and nullif(btrim(coalesce(_email,'')),'') is null then return null; end if;
  if nullif(btrim(coalesce(_phone,'')),'') is not null then
    select id into _id from public.crm_guests where restaurant_id=_restaurant_id and phone=btrim(_phone) limit 1;
  end if;
  if _id is null and nullif(btrim(coalesce(_email,'')),'') is not null then
    select id into _id from public.crm_guests where restaurant_id=_restaurant_id and lower(email)=lower(btrim(_email)) limit 1;
  end if;
  if _id is null then
    insert into public.crm_guests(restaurant_id,name,phone,email)
    values(_restaurant_id,nullif(btrim(coalesce(_name,'')),''),nullif(btrim(coalesce(_phone,'')),''),nullif(lower(btrim(coalesce(_email,''))),'')) returning id into _id;
  else
    update public.crm_guests set
      name=coalesce(nullif(btrim(coalesce(_name,'')),''),name),
      phone=coalesce(nullif(btrim(coalesce(_phone,'')),''),phone),
      email=coalesce(nullif(lower(btrim(coalesce(_email,''))),''),email),
      updated_at=now()
    where id=_id;
  end if;
  insert into public.crm_loyalty_accounts(guest_id,restaurant_id) values(_id,_restaurant_id) on conflict(guest_id) do nothing;
  return _id;
end;
$$;

create or replace function public.place_public_order_v2(
  _qr_token text,_items jsonb,_notes text default null,_guest_name text default null,_guest_phone text default null,_guest_email text default null
) returns table(order_id uuid,order_number text,public_token text,total numeric,currency text)
language plpgsql
security definer
set search_path=''
as $$
declare _result record; _restaurant_id uuid; _guest_id uuid;
begin
  perform app.enforce_public_rate_limit('order:'||coalesce(_qr_token,''),8,60);
  select t.restaurant_id into _restaurant_id from public.restaurant_tables t where t.qr_token=btrim(_qr_token) and t.is_active limit 1;
  if _restaurant_id is null then raise exception 'table not found'; end if;
  select * into _result from app.place_public_order(_qr_token,_items,_notes);
  _guest_id:=app.upsert_order_guest(_restaurant_id,_guest_name,_guest_phone,_guest_email);
  update public.orders set
    guest_id=_guest_id,
    guest_name=nullif(btrim(coalesce(_guest_name,'')),''),
    guest_phone=nullif(btrim(coalesce(_guest_phone,'')),''),
    guest_email=nullif(lower(btrim(coalesce(_guest_email,''))),'')
  where id=_result.order_id;
  return query select _result.order_id,_result.order_number,_result.public_token,_result.total,_result.currency;
end;
$$;
revoke all on function public.place_public_order_v2(text,jsonb,text,text,text,text) from public;
grant execute on function public.place_public_order_v2(text,jsonb,text,text,text,text) to anon,authenticated;

create or replace function app.on_paid_order_guest()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare _enabled boolean; _points integer; _rate numeric;
begin
  if new.payment_status='paid' and old.payment_status is distinct from new.payment_status and new.guest_id is not null then
    update public.crm_guests set visits=visits+1,lifetime_spend=lifetime_spend+new.total,last_visit_at=now(),updated_at=now() where id=new.guest_id;
    select enable_loyalty,loyalty_points_per_currency into _enabled,_rate from public.restaurant_settings where restaurant_id=new.restaurant_id;
    if coalesce(_enabled,false) then
      _points:=floor(new.total*coalesce(_rate,10))::integer;
      if _points>0 then
        insert into public.crm_loyalty_ledger(restaurant_id,guest_id,points,reason,source_order_id)
        values(new.restaurant_id,new.guest_id,_points,'Order reward',new.id)
        on conflict do nothing;
        if found then
          update public.crm_loyalty_accounts set points=points+_points,updated_at=now() where guest_id=new.guest_id;
        end if;
      end if;
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_paid_order_guest on public.orders;
create trigger trg_paid_order_guest after update of payment_status on public.orders
for each row execute function app.on_paid_order_guest();

create or replace function public.issue_gift_card(_restaurant_id uuid,_value numeric,_guest_id uuid default null,_expires_at timestamptz default null)
returns text
language plpgsql
security definer
set search_path=''
as $$
declare _code text;
begin
  if not (app.has_capability(_restaurant_id,'manage_payments') or app.has_capability(_restaurant_id,'manage_restaurant') or app.is_super_admin()) then
    raise exception 'Payment access is required';
  end if;
  if coalesce(_value,0)<=0 then raise exception 'Gift card value must be positive'; end if;
  _code:=upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));
  insert into public.crm_gift_cards(restaurant_id,code,initial_value,balance,guest_id,expires_at)
  values(_restaurant_id,_code,_value,_value,_guest_id,_expires_at);
  return _code;
end;
$$;
revoke all on function public.issue_gift_card(uuid,numeric,uuid,timestamptz) from public,anon;
grant execute on function public.issue_gift_card(uuid,numeric,uuid,timestamptz) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 5) Workforce / time clock
-- ---------------------------------------------------------------------------
create table if not exists public.staff_time_entries (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid not null references public.staff(id) on delete cascade,
  clock_in timestamptz not null default now(),
  clock_out timestamptz,
  break_minutes integer not null default 0 check(break_minutes>=0),
  notes text not null default '',
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create unique index if not exists staff_time_entries_one_open_idx on public.staff_time_entries(staff_id) where clock_out is null;
create index if not exists staff_time_entries_restaurant_clock_idx on public.staff_time_entries(restaurant_id,clock_in desc);
create table if not exists public.staff_leave_requests (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  staff_id uuid not null references public.staff(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text not null default '',
  status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check(end_date>=start_date)
);
alter table public.staff_time_entries enable row level security;
alter table public.staff_leave_requests enable row level security;
drop policy if exists staff_time_entries_select on public.staff_time_entries;
create policy staff_time_entries_select on public.staff_time_entries for select to authenticated using(
  app.has_capability(restaurant_id,'manage_shifts')
  or exists(select 1 from public.staff s where s.id=staff_id and s.auth_user_id=(select auth.uid()))
);
drop policy if exists staff_leave_requests_select on public.staff_leave_requests;
create policy staff_leave_requests_select on public.staff_leave_requests for select to authenticated using(
  app.has_capability(restaurant_id,'manage_shifts')
  or exists(select 1 from public.staff s where s.id=staff_id and s.auth_user_id=(select auth.uid()))
);
grant select on public.staff_time_entries,public.staff_leave_requests to authenticated;
revoke insert,update,delete on public.staff_time_entries,public.staff_leave_requests from authenticated;

create or replace function public.toggle_time_clock(_restaurant_id uuid)
returns table(action text,entry_id uuid,at timestamptz)
language plpgsql
security definer
set search_path=''
as $$
declare _staff_id uuid; _entry uuid; _at timestamptz:=now();
begin
  select id into _staff_id from public.staff
  where restaurant_id=_restaurant_id and auth_user_id=(select auth.uid()) and is_active limit 1;
  if _staff_id is null then raise exception 'Active staff profile not found'; end if;
  select id into _entry from public.staff_time_entries where staff_id=_staff_id and clock_out is null order by clock_in desc limit 1 for update;
  if _entry is null then
    insert into public.staff_time_entries(restaurant_id,staff_id,clock_in) values(_restaurant_id,_staff_id,_at) returning id into _entry;
    return query select 'clocked_in'::text,_entry,_at;
  else
    update public.staff_time_entries set clock_out=_at where id=_entry;
    return query select 'clocked_out'::text,_entry,_at;
  end if;
end;
$$;
revoke all on function public.toggle_time_clock(uuid) from public,anon;
grant execute on function public.toggle_time_clock(uuid) to authenticated,service_role;

create or replace function public.submit_leave_request(_restaurant_id uuid,_start date,_end date,_reason text default '')
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare _staff_id uuid; _id uuid;
begin
  select id into _staff_id from public.staff where restaurant_id=_restaurant_id and auth_user_id=(select auth.uid()) and is_active limit 1;
  if _staff_id is null then raise exception 'Active staff profile not found'; end if;
  if _end<_start then raise exception 'Invalid leave dates'; end if;
  insert into public.staff_leave_requests(restaurant_id,staff_id,start_date,end_date,reason)
  values(_restaurant_id,_staff_id,_start,_end,left(coalesce(_reason,''),1000)) returning id into _id;
  return _id;
end;
$$;
revoke all on function public.submit_leave_request(uuid,date,date,text) from public,anon;
grant execute on function public.submit_leave_request(uuid,date,date,text) to authenticated,service_role;

create or replace function public.review_leave_request(_request_id uuid,_status text)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare _restaurant_id uuid;
begin
  select restaurant_id into _restaurant_id from public.staff_leave_requests where id=_request_id;
  if _restaurant_id is null then raise exception 'Leave request not found'; end if;
  if not (app.has_capability(_restaurant_id,'manage_shifts') or app.has_capability(_restaurant_id,'manage_restaurant') or app.is_super_admin()) then raise exception 'Shift management access is required'; end if;
  if _status not in ('approved','rejected') then raise exception 'Invalid review status'; end if;
  update public.staff_leave_requests set status=_status,reviewed_by=(select auth.uid()),reviewed_at=now() where id=_request_id and status='pending';
end;
$$;
revoke all on function public.review_leave_request(uuid,text) from public,anon;
grant execute on function public.review_leave_request(uuid,text) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 6) Supplier invoice matching / accounting
-- ---------------------------------------------------------------------------
create table if not exists public.erp_supplier_invoices (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  supplier_id uuid references public.erp_suppliers(id) on delete set null,
  procurement_request_id uuid references public.erp_procurement_requests(id) on delete set null,
  invoice_number text not null,
  invoice_date date not null default current_date,
  amount numeric not null check(amount>=0),
  tax_amount numeric not null default 0 check(tax_amount>=0),
  status text not null default 'draft' check(status in ('draft','matched','approved','paid','void')),
  file_url text,
  expense_id uuid references public.erp_expenses(id) on delete set null,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(restaurant_id,invoice_number)
);
create index if not exists erp_supplier_invoices_restaurant_status_idx on public.erp_supplier_invoices(restaurant_id,status,invoice_date desc);
alter table public.erp_supplier_invoices enable row level security;
drop policy if exists erp_supplier_invoices_manage on public.erp_supplier_invoices;
create policy erp_supplier_invoices_manage on public.erp_supplier_invoices for all to authenticated using(
  app.has_capability(restaurant_id,'manage_finance') or app.has_capability(restaurant_id,'manage_procurement') or app.has_capability(restaurant_id,'manage_restaurant')
) with check(
  app.has_capability(restaurant_id,'manage_finance') or app.has_capability(restaurant_id,'manage_procurement') or app.has_capability(restaurant_id,'manage_restaurant')
);
grant select,insert,update on public.erp_supplier_invoices to authenticated;

-- ---------------------------------------------------------------------------
-- 7) Multi-location / HQ grouping
-- ---------------------------------------------------------------------------
create table if not exists public.restaurant_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.restaurant_group_members (
  group_id uuid not null references public.restaurant_groups(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(group_id,restaurant_id)
);
create index if not exists restaurant_group_members_restaurant_idx on public.restaurant_group_members(restaurant_id);
alter table public.restaurant_groups enable row level security;
alter table public.restaurant_group_members enable row level security;
drop policy if exists restaurant_groups_owner on public.restaurant_groups;
create policy restaurant_groups_owner on public.restaurant_groups for all to authenticated using(owner_user_id=(select auth.uid()) or app.is_super_admin()) with check(owner_user_id=(select auth.uid()) or app.is_super_admin());
drop policy if exists restaurant_group_members_select on public.restaurant_group_members;
create policy restaurant_group_members_select on public.restaurant_group_members for select to authenticated using(
  exists(select 1 from public.restaurant_groups g where g.id=group_id and (g.owner_user_id=(select auth.uid()) or app.is_super_admin()))
  or app.has_restaurant_access(restaurant_id)
);
drop policy if exists restaurant_group_members_manage on public.restaurant_group_members;
create policy restaurant_group_members_manage on public.restaurant_group_members for all to authenticated using(
  exists(select 1 from public.restaurant_groups g where g.id=group_id and (g.owner_user_id=(select auth.uid()) or app.is_super_admin()))
) with check(
  exists(select 1 from public.restaurant_groups g where g.id=group_id and (g.owner_user_id=(select auth.uid()) or app.is_super_admin()))
);
grant select,insert,update,delete on public.restaurant_groups,public.restaurant_group_members to authenticated;

-- ---------------------------------------------------------------------------
-- 8) SaaS usage / commercial controls
-- ---------------------------------------------------------------------------
create table if not exists public.saas_usage_daily (
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  usage_date date not null default current_date,
  orders_count integer not null default 0,
  active_staff integer not null default 0,
  tables_count integer not null default 0,
  menu_items_count integer not null default 0,
  storage_bytes bigint not null default 0,
  primary key(restaurant_id,usage_date)
);
alter table public.saas_usage_daily enable row level security;
drop policy if exists saas_usage_daily_select on public.saas_usage_daily;
create policy saas_usage_daily_select on public.saas_usage_daily for select to authenticated using(
  app.is_super_admin() or app.has_capability(restaurant_id,'manage_restaurant')
);
grant select on public.saas_usage_daily to authenticated;

create or replace function public.refresh_restaurant_usage(_restaurant_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if not (app.is_super_admin() or app.has_capability(_restaurant_id,'manage_restaurant')) then raise exception 'Restaurant management access is required'; end if;
  insert into public.saas_usage_daily(restaurant_id,usage_date,orders_count,active_staff,tables_count,menu_items_count)
  select _restaurant_id,current_date,
    (select count(*) from public.orders where restaurant_id=_restaurant_id and created_at>=date_trunc('month',now())),
    (select count(*) from public.staff where restaurant_id=_restaurant_id and is_active),
    (select count(*) from public.restaurant_tables where restaurant_id=_restaurant_id and is_active),
    (select count(*) from public.menu_items where restaurant_id=_restaurant_id and is_available)
  on conflict(restaurant_id,usage_date) do update set
    orders_count=excluded.orders_count,active_staff=excluded.active_staff,tables_count=excluded.tables_count,menu_items_count=excluded.menu_items_count;
end;
$$;
revoke all on function public.refresh_restaurant_usage(uuid) from public,anon;
grant execute on function public.refresh_restaurant_usage(uuid) to authenticated,service_role;

-- Supporting indexes for newly added foreign keys.
create index if not exists orders_guest_id_idx on public.orders(guest_id) where guest_id is not null;
create index if not exists staff_time_entries_staff_idx on public.staff_time_entries(staff_id,clock_in desc);
create index if not exists staff_leave_requests_staff_idx on public.staff_leave_requests(staff_id,created_at desc);
create index if not exists crm_gift_cards_guest_idx on public.crm_gift_cards(guest_id) where guest_id is not null;
create index if not exists erp_supplier_invoices_procurement_idx on public.erp_supplier_invoices(procurement_request_id) where procurement_request_id is not null;
create index if not exists erp_supplier_invoices_expense_idx on public.erp_supplier_invoices(expense_id) where expense_id is not null;
