// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { createAccessTokenResolver } from '@/lib/session-token'

const resolveToken = createAccessTokenResolver({
  getSession: () => supabase.auth.getSession(),
  refreshSession: () => supabase.auth.refreshSession(),
})

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await resolveToken()

    return next({
      // Authorization may be owned/replaced by the hosting proxy. A dedicated
      // header keeps the Supabase user token unambiguous end to end.
      headers: token ? { 'x-supabase-access-token': token } : {},
    })
  },
)
