// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with elevated secret/service key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import { quickServeSupabase } from './public-config';
import type { Database } from './types';

function resolveSecretKey(): string | undefined {
  // Lovable reserves SUPABASE_ for managed secrets. Use the custom server-only
  // key for the external sign-in project before considering managed defaults.
  const customSecret = process.env['SUPAB_SECRET_KEY']?.trim();
  if (customSecret) return customSecret;

  // Prefer the new Supabase secret key. Keep the legacy service-role key as a
  // backwards-compatible fallback for existing projects.
  const directSecret = process.env['SUPABASE_SECRET_KEY'];
  if (directSecret) return directSecret;

  const secretKeys = process.env['SUPABASE_SECRET_KEYS'];
  if (secretKeys) {
    try {
      const parsed = JSON.parse(secretKeys) as Record<string, string>;
      if (parsed['default']) return parsed['default'];
      const first = Object.values(parsed).find((value) => typeof value === 'string' && value.length > 0);
      if (first) return first;
    } catch {
      // Fall through to the legacy key.
    }
  }

  return process.env['SUPABASE_SERVICE_ROLE_KEY'];
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = quickServeSupabase.url;
  const SUPABASE_ADMIN_KEY = resolveSecretKey();

  if (!SUPABASE_URL || !SUPABASE_ADMIN_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_ADMIN_KEY ? ['SUPAB_SECRET_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ADMIN_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with elevated secret/service key.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
